"""OrdersRepository — read/write access to the orders table.

Scope (M3 Cycle 9):
  - create_order(order_id, account_id, instrument, account_type, order_type, direction, units)
  - get_by_order_id(order_id) -> dict | None

order_id is a ULID generated by the application layer (D1 §6.4).
Status FSM: PENDING -> SUBMITTED -> FILLED | CANCELED | FAILED (no backward transitions).
Common Keys physical columns are M5 scope.
"""

from __future__ import annotations

from sqlalchemy import text

from fx_ai_trading.repositories.base import RepositoryBase

_COLUMNS = (
    "order_id",
    "client_order_id",
    "trading_signal_id",
    "account_id",
    "instrument",
    "account_type",
    "order_type",
    "direction",
    "units",
    "status",
    "submitted_at",
    "filled_at",
    "canceled_at",
    "correlation_id",
    "created_at",
)


class OrdersRepository(RepositoryBase):
    """Read/write interface for the orders table."""

    def get_by_order_id(self, order_id: str) -> dict | None:
        """Return the order row for *order_id*, or None if not found."""
        with self._engine.connect() as conn:
            row = conn.execute(
                text(
                    "SELECT order_id, client_order_id, trading_signal_id,"
                    " account_id, instrument, account_type, order_type,"
                    " direction, units, status, submitted_at, filled_at,"
                    " canceled_at, correlation_id, created_at"
                    " FROM orders WHERE order_id = :order_id"
                ),
                {"order_id": order_id},
            ).fetchone()
        if row is None:
            return None
        return dict(zip(_COLUMNS, row, strict=True))

    def create_order(
        self,
        order_id: str,
        account_id: str,
        instrument: str,
        account_type: str,
        order_type: str,
        direction: str,
        units: str,
        *,
        client_order_id: str | None = None,
        trading_signal_id: str | None = None,
        correlation_id: str | None = None,
    ) -> None:
        """Insert a new order row with status PENDING."""
        with self._engine.begin() as conn:
            conn.execute(
                text(
                    "INSERT INTO orders"
                    " (order_id, client_order_id, trading_signal_id,"
                    "  account_id, instrument, account_type, order_type,"
                    "  direction, units, correlation_id)"
                    " VALUES"
                    " (:order_id, :client_order_id, :trading_signal_id,"
                    "  :account_id, :instrument, :account_type, :order_type,"
                    "  :direction, :units, :correlation_id)"
                ),
                {
                    "order_id": order_id,
                    "client_order_id": client_order_id,
                    "trading_signal_id": trading_signal_id,
                    "account_id": account_id,
                    "instrument": instrument,
                    "account_type": account_type,
                    "order_type": order_type,
                    "direction": direction,
                    "units": units,
                    "correlation_id": correlation_id,
                },
            )
