# ruff: noqa: E501 -- a catalogue of Japanese prose and rendered table rows
"""The candidate expected-return sources, the prior-evidence map, and a declared ranking.

`NON_DECISION_BEARING_EXPLORATORY_ONLY` · `RESEARCH_SCRATCH_NON_AUTHORITATIVE`.

Every candidate names the prior evidence it overlaps, classified exactly as that
evidence stands in the ledger (`scripts/research/round_a/ledger.py`), the
decision-grade inventory (`artifacts/research/feasibility/inventory.json`) or a
merged phase record. A candidate that only renames a closed family is kept in the
catalogue and marked excluded, so the exclusion itself is visible.

The ranking is a judgement with declared weights, not a measurement. Scores are
set from mechanism, prior evidence, data access and the capacity arithmetic in
`capacity.py` — never from a backtest, because none was run.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Final

#: Prior-evidence classes, in the ruling's words (§20).
EVIDENCE_CLASSES: Final[tuple[str, ...]] = (
    "CLOSED",
    "NOT_SUPPORTED",
    "NOT_DECISION_GRADE",
    "SUSPENDED",
    "OPEN",
    "ENGINEERING_RESULT",
    "UNTESTED",
)


@dataclass(frozen=True, slots=True)
class Evidence:
    ref: str
    what: str
    klass: str
    status: str


#: The map of what the programme has established. `ref` is a ledger id, an
#: inventory candidate id, or a merged PR number; `status` is quoted from it.
EVIDENCE_MAP: Final[tuple[Evidence, ...]] = (
    Evidence("H-001", "M15 indicator zoo の絶対方向", "CLOSED", "CLOSED"),
    Evidence("H-002", "session / ATR / ADX / spread gate", "CLOSED", "CLOSED"),
    Evidence("H-003", "pair relative strength（通貨 exposure が 96%）", "CLOSED", "CLOSED"),
    Evidence("H-004", "raw / simple price-feature の方向 ML", "CLOSED", "CLOSED"),
    Evidence(
        "H-006",
        "4〜6 日 reversal family",
        "CLOSED",
        "MULTI_DAY_REVERSAL_FAILED_SUPPLEMENTAL_HISTORY_REPLICATION",
    ),
    Evidence(
        "H-007",
        "mirror momentum（反証ではなく検出力不足）",
        "CLOSED",
        "MULTI_DAY_MOMENTUM_UNRESOLVED_IN_FRESH_EXPLORATORY_HISTORY",
    ),
    Evidence("H-009", "単純な HTF / D1 trend 条件付け", "CLOSED", "CLOSED — Round A"),
    Evidence(
        "H-010",
        "price-path structure（VR<1、収益化不能）",
        "CLOSED",
        "CLOSED - real but unharvestable microstructure",
    ),
    Evidence("H-011", "retrace geometry（B′-2）", "OPEN", "OPEN"),
    Evidence(
        "H-012",
        "monthly TSMOM",
        "NOT_SUPPORTED",
        "MONTHLY_TSMOM_NOT_SUPPORTED_IN_EXISTING_PRICE_HISTORY",
    ),
    Evidence(
        "H-013",
        "retrace geometry（clean retest）",
        "CLOSED",
        "RETRACE_GEOMETRY_FAMILY_DROPPED_AFTER_CLEAN_RETEST",
    ),
    Evidence(
        "H-014",
        "path linear monetization（固定 horizon、線形 selector）",
        "CLOSED",
        "PATH_STRUCTURE_STATISTICALLY_REAL_BUT_ECONOMICALLY_TOO_SMALL",
    ),
    Evidence(
        "H-015",
        "tick volume → 将来の活動・volatility",
        "OPEN",
        "TICK_VOLUME_INFORMATION_INCREMENTALLY_DISTINCT",
    ),
    Evidence(
        "H-016",
        "政策金利 proxy の carry（level / change）",
        "NOT_SUPPORTED",
        "CARRY_EDGE_NOT_SUPPORTED",
    ),
    Evidence(
        "H-017",
        "tick volume の方向 / timing",
        "CLOSED",
        "CLOSED - volume is a volatility variable, not a timing one",
    ),
    Evidence(
        "H-018",
        "政策金利変更日の movement structure（cost 優位は不成立）",
        "OPEN",
        "CALENDAR_EVENT_MOVEMENT_STRUCTURE_SUPPORTED",
    ),
    Evidence(
        "H-019",
        "forward-known event の movement（方向なし）",
        "OPEN",
        "FORWARD_KNOWN_EVENT_OPPORTUNITY_STRUCTURE_SUPPORTED",
    ),
    Evidence(
        "H-020",
        "USD CPI の nowcast surprise 方向",
        "NOT_SUPPORTED",
        "MACRO_SURPRISE_DIRECTIONAL_EDGE_NOT_SUPPORTED",
    ),
    Evidence("H-021", "COT の tested cells", "NOT_SUPPORTED", "COT_EDGE_NOT_SUPPORTED"),
    Evidence(
        "H-022",
        "model learning（3 track、当時の gate）",
        "NOT_DECISION_GRADE",
        "MODEL_LEARNING_NOT_DECISION_GRADE_UNDER_CURRENT_DEVELOPMENT_GATE",
    ),
    Evidence(
        "H-023",
        "linear continuous currency expected-return architecture",
        "NOT_SUPPORTED",
        "CONTINUOUS_CURRENCY_PORTFOLIO_ARCHITECTURE_NOT_SUPPORTED_IN_SEEN_DEVELOPMENT",
    ),
    Evidence(
        "H-024",
        "post-hoc 通貨 reversal（5/20/60 日のみ）",
        "CLOSED",
        "POST_HOC_EXPLORATORY_NON_DECISION_BEARING",
    ),
    Evidence(
        "#471",
        "event-day の cost 優位",
        "NOT_SUPPORTED",
        "EVENT_DAY_COST_ADVANTAGE_NOT_ESTABLISHED",
    ),
    Evidence(
        "#475",
        "near-touch passive 執行",
        "NOT_SUPPORTED",
        "passive 執行は、この 2 パネルで意味のあるコスト削減を与えられない。",
    ),
    Evidence(
        "#475",
        "clock / London fix の構造",
        "SUSPENDED",
        "CLOCK_STRUCTURE_NOT_DECISION_GRADE_AT_CURRENT_EXECUTION_FRONTIER",
    ),
    Evidence(
        "#477",
        "non-USD surprise relative",
        "SUSPENDED",
        "NON_USD_SURPRISE_DATA_NOT_DECISION_GRADE_SKIP",
    ),
    Evidence(
        "#478",
        "seen data 上の長 horizon 構造（検出力不足）",
        "NOT_DECISION_GRADE",
        "CURRENT_SEEN_DATA_FX_RESEARCH_SPACE_EXHAUSTED",
    ),
    Evidence(
        "C09",
        "yield differential change（未実行）",
        "NOT_DECISION_GRADE",
        "NO_DECISION_GRADE_PASS_REGION",
    ),
    Evidence(
        "C10",
        "equity risk regime conditioning（未実行）",
        "NOT_DECISION_GRADE",
        "NO_DECISION_GRADE_PASS_REGION",
    ),
    Evidence(
        "C11",
        "commodity link response（未実行）",
        "NOT_DECISION_GRADE",
        "NO_DECISION_GRADE_PASS_REGION",
    ),
    Evidence(
        "C01",
        "central bank decision response（未実行）",
        "NOT_DECISION_GRADE",
        "NO_DECISION_GRADE_PASS_REGION",
    ),
    Evidence(
        "C03",
        "session handover relative（未実行）",
        "NOT_DECISION_GRADE",
        "NO_DECISION_GRADE_PASS_REGION",
    ),
    Evidence(
        "C04",
        "benchmark fix flow（未実行）",
        "NOT_DECISION_GRADE",
        "NO_DECISION_GRADE_PASS_REGION",
    ),
    Evidence(
        "C05",
        "month-end rebalancing flow（未実行、事象数が下限未満）",
        "NOT_DECISION_GRADE",
        "NO_DECISION_GRADE_PASS_REGION",
    ),
    Evidence(
        "C06",
        "factor-neutral residual value（未実行）",
        "NOT_DECISION_GRADE",
        "NO_DECISION_GRADE_PASS_REGION",
    ),
    Evidence(
        "C07",
        "cross-sectional dispersion state（未実行）",
        "NOT_DECISION_GRADE",
        "NO_DECISION_GRADE_PASS_REGION",
    ),
    Evidence(
        "C13",
        "timeframe disagreement state（未実行）",
        "NOT_DECISION_GRADE",
        "NO_DECISION_GRADE_PASS_REGION",
    ),
    Evidence("C21", "futures positioning（COT 由来）", "CLOSED", "PRIOR_FAMILY_CLOSED"),
    Evidence("C22", "carry level", "CLOSED", "PRIOR_FAMILY_CLOSED"),
    Evidence(
        "C12",
        "volatility regime transition（未実行）",
        "NOT_DECISION_GRADE",
        "NO_DECISION_GRADE_PASS_REGION",
    ),
    Evidence(
        "C14",
        "latent regime state（未実行）",
        "NOT_DECISION_GRADE",
        "NO_DECISION_GRADE_PASS_REGION",
    ),
    Evidence("C02", "macro surprise intraday", "SUSPENDED", "DATA_INTEGRITY_BLOCKED"),
    Evidence("C20", "broker order flow", "SUSPENDED", "DATA_INTEGRITY_BLOCKED"),
    Evidence(
        "#482",
        "efficiency bundle（band・部分 rebalance）の turnover 低減。裁定 token TURNOVER_REDUCTION_MECHANISM_SUPPORTED は H-023 に記録",
        "ENGINEERING_RESULT",
        "bundle は本来の目的（turnover 削減）は果たした",
    ),
    Evidence(
        "#476",
        "unit-consistent feasibility gate",
        "ENGINEERING_RESULT",
        "FEASIBILITY_GATE_V2_PROSPECTIVE_ONLY",
    ),
    Evidence("—", "市場利回り（2 年・曲線）による repricing", "UNTESTED", "未取得・未検定"),
    Evidence("—", "実質為替レート / valuation", "UNTESTED", "未取得・未検定"),
    Evidence("—", "event 日の市場 repricing を方向ソースにする構造", "UNTESTED", "未検定"),
)

EXCLUDED: Final[str] = "excluded_renames_or_rescues_a_closed_family"
BLOCKED: Final[str] = "blocked_by_data_access"
ACTIVE: Final[str] = "eligible"


@dataclass(frozen=True, slots=True)
class Candidate:
    cid: str
    direction: str
    name: str
    mechanism: str
    information: str
    target: str
    horizon: str
    architecture: str
    turnover: str
    utilisation: str
    breadth: str
    data: str
    access: str
    overlap: tuple[str, ...]
    why_not_falsified: str
    capacity: str
    ml_role: str
    eligibility: str
    #: judgement scores, 1 (worst) .. 5 (best) for gains; 1 (lightest) .. 5 for burdens
    p_real: int
    magnitude: int
    utilisation_score: int
    breadth_score: int
    robustness: int
    information_gain: int
    turnover_cost: int
    complexity: int
    overfit_risk: int
    data_burden: int
    engineering_burden: int
    notes: tuple[str, ...] = field(default_factory=tuple)


#: Declared before any candidate was scored. Gains add, burdens subtract; the two
#: factors the ruling puts first — P(real edge) and information gain — count twice.
GAIN_WEIGHTS: Final[dict[str, int]] = {
    "p_real": 2,
    "magnitude": 1,
    "utilisation_score": 1,
    "breadth_score": 1,
    "robustness": 1,
    "information_gain": 2,
}
BURDEN_WEIGHTS: Final[dict[str, int]] = {
    "turnover_cost": 1,
    "complexity": 1,
    "overfit_risk": 1,
    "data_burden": 1,
    "engineering_burden": 1,
}


def score(candidate: Candidate) -> int:
    gains = sum(weight * getattr(candidate, name) for name, weight in GAIN_WEIGHTS.items())
    burdens = sum(weight * getattr(candidate, name) for name, weight in BURDEN_WEIGHTS.items())
    return gains - burdens


C: Final[tuple[Candidate, ...]] = (
    Candidate(
        cid="S01",
        direction="A",
        name="front-end 金利差 repricing → 通貨相対リターン",
        mechanism="市場が織り込む政策パス（2 年金利）の相対変化に、FX が数日〜数週遅れて追随する",
        information="各国 2 年国債利回りの日次変化（通貨ごとに対 G10 平均）",
        target="通貨の 5〜20 日先 excess return",
        horizon="5〜20 日",
        architecture="continuous currency book（Track 1 の執行層を再利用）",
        turnover="18〜43 RT/年/単位 gross",
        utilisation="常時",
        breadth="8 通貨（実効 4）",
        data="US 2y は FRED 日次 1976〜。非 US 2y は各中銀（BoE・BoC・MOF は到達、ECB・Bundesbank・SNB は本環境で証明書エラー、RBA・RBNZ は 403）",
        access="無料・認証不要（取得は承認後）",
        overlap=("H-016", "C09", "H-023"),
        why_not_falsified="H-016 は政策金利（階段関数）の level / change で、市場利回りは未取得。C09 は horizon gate で未実行",
        capacity="net 0.5 に 20 日 IC 12.8%（日次換算 2.9%）。prior は net 0.2〜0.5",
        ml_role="不要（線形 baseline）。閾値相互作用は S16 で増分のみ",
        eligibility=ACTIVE,
        p_real=3,
        magnitude=3,
        utilisation_score=5,
        breadth_score=4,
        robustness=3,
        information_gain=5,
        turnover_cost=2,
        complexity=2,
        overfit_risk=2,
        data_burden=3,
        engineering_burden=2,
    ),
    Candidate(
        cid="S02",
        direction="A",
        name="曲線 slope / curvature 差の変化",
        mechanism="成長・インフレ期待の相対変化が通貨需要を動かす",
        information="各国 2s10s・曲率の日次変化",
        target="通貨の 20〜60 日先 excess return",
        horizon="20〜60 日",
        architecture="continuous currency book",
        turnover="8〜18 RT/年/単位 gross",
        utilisation="常時",
        breadth="8 通貨（実効 4）",
        data="非 US 10y の日次は中銀ソース（FRED の OECD 系列は月次のみ）",
        access="無料・認証不要（取得は承認後）",
        overlap=("C09",),
        why_not_falsified="曲線形状は一度も取得していない",
        capacity="net 0.5 に 60 日 IC 17.8%。prior は net 0.1〜0.3",
        ml_role="不要",
        eligibility=ACTIVE,
        p_real=2,
        magnitude=2,
        utilisation_score=5,
        breadth_score=4,
        robustness=2,
        information_gain=3,
        turnover_cost=1,
        complexity=2,
        overfit_risk=3,
        data_burden=4,
        engineering_burden=2,
    ),
    Candidate(
        cid="S03",
        direction="G",
        name="中銀会合日の市場 repricing → 会合後 drift",
        mechanism="会合日に市場が織り込んだ政策パスの変化（2 年金利の当日変化）に、FX が会合後数日かけて追随する（under-reaction）",
        information="G10 中銀会合カレンダー + 会合日の 2 年金利変化",
        target="会合通貨の 1〜5 日先 excess return（repricing の方向）",
        horizon="1〜5 日",
        architecture="event book（idle 時は保有なし、Track 1 の執行層で差分売買）",
        turnover="事象あたり 1 往復、約 60 事象/年",
        utilisation="約 9% の日",
        breadth="8 中銀",
        data="会合カレンダーは Fed・ECB・BoJ・RBA を取得済み、BoE・BoC・SNB・RBNZ は追加要。2 年金利は S01 と同じ",
        access="無料・認証不要（取得は承認後）",
        overlap=("C01", "H-019", "H-018", "H-016"),
        why_not_falsified="H-018/H-019 は event の movement のみで方向ソースを持たず、H-016 は決定そのもので市場 repricing ではない。C01 は未実行",
        capacity="n=60・3 日保有で net 0.5 に事象あたり 10.9 bp（課金）/ 6.7 bp（pair）。事象数が少なく検出力が律速",
        ml_role="不要",
        eligibility=ACTIVE,
        p_real=3,
        magnitude=2,
        utilisation_score=1,
        breadth_score=3,
        robustness=3,
        information_gain=4,
        turnover_cost=2,
        complexity=2,
        overfit_risk=2,
        data_burden=3,
        engineering_burden=2,
    ),
    Candidate(
        cid="S04",
        direction="G",
        name="主要指標発表日の市場 repricing → 発表後 drift",
        mechanism="surprise を consensus ではなく当日の市場 repricing（2 年金利の変化）で測り、発表後数日の FX drift を狙う",
        information="G10 主要指標の発表日 + 当日の 2 年金利変化",
        target="発表通貨の 1〜5 日先 excess return",
        horizon="1〜5 日",
        architecture="event book",
        turnover="事象あたり 1 往復、150〜300 事象/年",
        utilisation="22〜74% の日",
        breadth="8 通貨",
        data="US 発表日は ALFRED を取得済み、非 US は発表日カレンダーが要る。2 年金利は S01 と同じ",
        access="無料・認証不要（取得は承認後）",
        overlap=("H-020", "C02", "#477", "H-019"),
        why_not_falsified="H-020 は US CPI の nowcast surprise で 1h〜1d・breadth 不足、C02 は時刻データの問題で blocked、#477 は検出力で skip。市場 repricing を surprise とする多日 drift は未検定。未 merge の #473 は survey consensus の USD 1h で検出力ある null",
        capacity="n=150〜300・2〜5 日保有で net 0.5 に事象あたり 8.4〜9.4 bp（課金）/ 4.2〜5.2 bp（pair）",
        ml_role="不要",
        eligibility=ACTIVE,
        p_real=2,
        magnitude=3,
        utilisation_score=3,
        breadth_score=4,
        robustness=2,
        information_gain=4,
        turnover_cost=3,
        complexity=3,
        overfit_risk=3,
        data_burden=4,
        engineering_burden=3,
        notes=(
            "#473 の null は announcement 効果が 1h に集中するなら多日 drift も弱いことを示唆する",
        ),
    ),
    Candidate(
        cid="S05",
        direction="B",
        name="株式・volatility shock → funding 通貨 vs 資源国通貨（時刻整合した lag）",
        mechanism="risk appetite の変化が funding / carry 通貨へ遅れて波及する",
        information="VIX（FRED 日次 1990〜）、S&P 500・Nikkei（FRED 日次）",
        target="JPY・CHF 対 AUD・NZD・CAD の 1〜5 日先 excess return",
        horizon="1〜5 日",
        architecture="continuous currency book",
        turnover="43〜100 RT/年/単位 gross",
        utilisation="常時",
        breadth="実効 2（risk 軸 1 本）",
        data="FRED で無料。FX 側は株式終値と同時刻に揃える必要（M1 archive で可能）",
        access="無料・認証不要",
        overlap=("C10", "H-016"),
        why_not_falsified="C10 は未実行。carry（H-016）は level で risk shock の lag ではない",
        capacity="breadth 2 のため必要 IC が約 1.4 倍に上がる。FX は 24h 連続取引で同時に織り込む prior が強い",
        ml_role="不要",
        eligibility=ACTIVE,
        p_real=2,
        magnitude=2,
        utilisation_score=5,
        breadth_score=2,
        robustness=2,
        information_gain=3,
        turnover_cost=3,
        complexity=2,
        overfit_risk=3,
        data_burden=2,
        engineering_burden=2,
    ),
    Candidate(
        cid="S06",
        direction="B",
        name="商品価格 → 資源国通貨（terms of trade lead）",
        mechanism="原油・金属の価格変化が交易条件経由で CAD・AUD・NZD に遅れて反映される",
        information="WTI・Brent（FRED 日次）。金属の日次は無料では限定的（銅は月次）",
        target="CAD・AUD・NZD の 5〜20 日先 excess return",
        horizon="5〜20 日",
        architecture="continuous currency book（3 通貨に集中）",
        turnover="18〜43 RT/年/単位 gross",
        utilisation="常時",
        breadth="実効 1〜2",
        data="原油は無料、金属・乳製品の日次は有料寄り",
        access="一部無料",
        overlap=("C11",),
        why_not_falsified="C11 は未実行",
        capacity="breadth が狭く、net 0.5 に必要な IC が高い。単独での年 5% は困難",
        ml_role="不要",
        eligibility=ACTIVE,
        p_real=2,
        magnitude=1,
        utilisation_score=4,
        breadth_score=1,
        robustness=2,
        information_gain=2,
        turnover_cost=2,
        complexity=2,
        overfit_risk=3,
        data_burden=3,
        engineering_burden=2,
    ),
    Candidate(
        cid="S07",
        direction="B",
        name="信用 spread・funding stress → USD・JPY・CHF",
        mechanism="funding 市場の緊張が安全通貨需要に先行する",
        information="US HY OAS（FRED 日次）、SOFR（2018〜）",
        target="USD・JPY・CHF の 5〜20 日先 excess return",
        horizon="5〜20 日",
        architecture="continuous currency book",
        turnover="18〜43 RT/年/単位 gross",
        utilisation="常時（効くのは stress 期のみの可能性）",
        breadth="実効 1〜2",
        data="FRED で無料",
        access="無料・認証不要",
        overlap=("C10",),
        why_not_falsified="未実行",
        capacity="stress 期に偏るため tail 集中が大きく、年間を通じた収益は小さい prior",
        ml_role="不要",
        eligibility=ACTIVE,
        p_real=2,
        magnitude=1,
        utilisation_score=2,
        breadth_score=1,
        robustness=2,
        information_gain=2,
        turnover_cost=2,
        complexity=2,
        overfit_risk=3,
        data_burden=2,
        engineering_burden=2,
    ),
    Candidate(
        cid="S08",
        direction="B",
        name="金利 volatility 状態 × FX",
        mechanism="金利 volatility の高低で FX の金利感応度が変わる",
        information="利回り変化から推定する rates vol（MOVE は有料）",
        target="S01 の条件付け",
        horizon="5〜20 日",
        architecture="S01 への条件付け",
        turnover="S01 と同程度",
        utilisation="常時",
        breadth="S01 と同じ",
        data="S01 と同じ",
        access="無料（MOVE は有料）",
        overlap=("C12", "H-002"),
        why_not_falsified="単独の return source ではなく条件付けで、S01 の base が正でなければ意味を持たない",
        capacity="S01 の増分のみ",
        ml_role="S16 と統合",
        eligibility=ACTIVE,
        p_real=1,
        magnitude=1,
        utilisation_score=3,
        breadth_score=3,
        robustness=1,
        information_gain=1,
        turnover_cost=2,
        complexity=3,
        overfit_risk=4,
        data_burden=3,
        engineering_burden=2,
    ),
    Candidate(
        cid="S09",
        direction="C",
        name="三角 residual（cross と合成 cross の乖離）",
        mechanism="pair 間の一時的な不整合の解消",
        information="20 pair の bid/ask",
        target="residual の縮小",
        horizon="秒〜分",
        architecture="高頻度",
        turnover="極めて高い",
        utilisation="断続",
        breadth="多い",
        data="M1 archive はあるが分解能が足りない",
        access="—",
        overlap=("H-010",),
        why_not_falsified="bid/ask を整合させると乖離は spread の内側に収まる（無裁定条件）",
        capacity="spread 内の構造で、構造的に cost を超えない",
        ml_role="—",
        eligibility=EXCLUDED,
        p_real=1,
        magnitude=1,
        utilisation_score=2,
        breadth_score=3,
        robustness=1,
        information_gain=1,
        turnover_cost=5,
        complexity=3,
        overfit_risk=3,
        data_burden=4,
        engineering_burden=4,
        notes=("H-010 の収益化不能な microstructure と同じ層",),
    ),
    Candidate(
        cid="S10",
        direction="C",
        name="通貨 complex 間の lead-lag 伝播（例: EUR→CHF、AUD→NZD）",
        mechanism="bloc の先行通貨の動きが追随通貨へ遅れて伝わる",
        information="通貨 excess return の intraday 系列",
        target="追随通貨の数時間先 return",
        horizon="数十分〜数時間",
        architecture="intraday currency book",
        turnover="100 RT/年/単位 gross 超",
        utilisation="常時",
        breadth="bloc 数（3〜4）",
        data="M1 archive（seen span のみ）",
        access="保有",
        overlap=("H-010", "H-003", "H-002"),
        why_not_falsified="aggregate の VR（H-010）は検定済みだが、bloc 間の cross lead-lag は未検定",
        capacity="半減期 1 日で net 0.5 に日次 IC 7%、intraday はさらに高い。FX の伝播は秒単位で裁定される prior",
        ml_role="不要",
        eligibility=ACTIVE,
        p_real=1,
        magnitude=2,
        utilisation_score=4,
        breadth_score=2,
        robustness=1,
        information_gain=2,
        turnover_cost=5,
        complexity=3,
        overfit_risk=4,
        data_burden=1,
        engineering_burden=3,
    ),
    Candidate(
        cid="S11",
        direction="C",
        name="動的共通 factor residual の reversal",
        mechanism="共通 factor から外れた通貨が戻る",
        information="通貨 excess return の rolling PCA residual",
        target="residual の 5〜20 日先縮小",
        horizon="5〜20 日",
        architecture="continuous currency book",
        turnover="18〜43",
        utilisation="常時",
        breadth="実効 4",
        data="保有",
        access="保有",
        overlap=("H-024", "C06", "H-023"),
        why_not_falsified="—（通貨 reversal の事後観察 H-024 と同形で、名前を変えた復活になる）",
        capacity="—",
        ml_role="—",
        eligibility=EXCLUDED,
        p_real=1,
        magnitude=2,
        utilisation_score=5,
        breadth_score=4,
        robustness=1,
        information_gain=1,
        turnover_cost=2,
        complexity=2,
        overfit_risk=5,
        data_burden=1,
        engineering_burden=1,
    ),
    Candidate(
        cid="S12",
        direction="D",
        name="相関 breakdown / dispersion 状態の relative value",
        mechanism="通常の共動から外れた pair が収束する",
        information="rolling 相関と dispersion",
        target="pair spread の 5〜20 日先",
        horizon="5〜20 日",
        architecture="pair relative-value book",
        turnover="18〜43",
        utilisation="断続",
        breadth="低い",
        data="保有",
        access="保有",
        overlap=("C07", "H-003", "H-024"),
        why_not_falsified="C07 は未実行だが、price 由来の収束は H-024 と隣接",
        capacity="#480 の A12 は構造的に年 2% 未満と試算",
        ml_role="不要",
        eligibility=ACTIVE,
        p_real=1,
        magnitude=1,
        utilisation_score=2,
        breadth_score=2,
        robustness=1,
        information_gain=1,
        turnover_cost=3,
        complexity=3,
        overfit_risk=4,
        data_burden=1,
        engineering_burden=2,
    ),
    Candidate(
        cid="S13",
        direction="D",
        name="実質為替レート valuation（PPP・実質金利 anchor）",
        mechanism="実質為替レートの長期均衡からの乖離が数か月〜数年で戻る（学術的な currency value premium）",
        information="各国 CPI（FRED 月次）と長期の FX 水準",
        target="通貨の 3〜12 か月先 excess return",
        horizon="3〜12 か月",
        architecture="continuous currency book（低 turnover）",
        turnover="約 5 RT/年/単位 gross",
        utilisation="常時",
        breadth="8 通貨（実効 4）",
        data="CPI は無料。検定には数十年の FX 履歴が要り、seen の 4.7 年では不能",
        access="無料（FX 長期履歴の read は保護 span 外に限り承認が要る）",
        overlap=("H-016", "H-012"),
        why_not_falsified="valuation は一度も検定していない。H-016 は carry、H-012 は momentum",
        capacity="net 0.5 に 120 日 IC 23%。学術 prior は G10 value 単独で net 0.2〜0.4、低 turnover の分散源",
        ml_role="不要",
        eligibility=ACTIVE,
        p_real=3,
        magnitude=2,
        utilisation_score=5,
        breadth_score=4,
        robustness=3,
        information_gain=4,
        turnover_cost=1,
        complexity=1,
        overfit_risk=2,
        data_burden=4,
        engineering_burden=2,
        notes=("seen data では答えられない。pre-2016-06-02 の公開 FX 履歴の承認が前提",),
    ),
    Candidate(
        cid="S14",
        direction="E",
        name="fast / medium / slow の price state 不一致",
        mechanism="horizon 間で状態が食い違うときの期待リターン",
        information="複数 horizon の price state",
        target="通貨の 5〜20 日先",
        horizon="5〜20 日",
        architecture="continuous currency book",
        turnover="18〜43",
        utilisation="常時",
        breadth="実効 4",
        data="保有",
        access="保有",
        overlap=("C13", "H-009", "H-023"),
        why_not_falsified="C13 は未実行だが、Track 1（5/20/60 日 + trend age の線形結合）が gross 負",
        capacity="price 由来の多 horizon 情報は H-023 で線形に使って負",
        ml_role="非線形の相互作用を仮説にしない限り不要",
        eligibility=ACTIVE,
        p_real=1,
        magnitude=2,
        utilisation_score=5,
        breadth_score=4,
        robustness=1,
        information_gain=1,
        turnover_cost=2,
        complexity=3,
        overfit_risk=5,
        data_burden=1,
        engineering_burden=1,
    ),
    Candidate(
        cid="S15",
        direction="E",
        name="volatility / trend の状態遷移（latent regime）",
        mechanism="状態の切り替わり直後に期待リターンが変わる",
        information="price 由来の regime 推定",
        target="通貨の 5〜20 日先",
        horizon="5〜20 日",
        architecture="continuous currency book",
        turnover="18〜43",
        utilisation="常時",
        breadth="実効 4",
        data="保有",
        access="保有",
        overlap=("C12", "C14", "H-002", "H-022"),
        why_not_falsified="C12・C14 は未実行。H-022 の regime-gain は一定 gross の book で増分が厳密に 0",
        capacity="状態は return source ではなく条件付け。base が負なら救済にならない",
        ml_role="HMM 等は未承認の複雑化になりやすい",
        eligibility=ACTIVE,
        p_real=1,
        magnitude=1,
        utilisation_score=4,
        breadth_score=3,
        robustness=1,
        information_gain=1,
        turnover_cost=2,
        complexity=4,
        overfit_risk=5,
        data_burden=1,
        engineering_burden=2,
    ),
    Candidate(
        cid="S16",
        direction="F",
        name="金利 repricing × volatility の閾値効果",
        mechanism="金利差の変化が効くのは risk 環境が落ち着いているときに限る、という相互作用",
        information="S01 + risk 状態（VIX 等）",
        target="S01 と同じ",
        horizon="5〜20 日",
        architecture="S01 の非線形増分",
        turnover="S01 よりやや高い",
        utilisation="常時",
        breadth="S01 と同じ",
        data="S01 + FRED",
        access="無料",
        overlap=("S01", "C10"),
        why_not_falsified="S01 の線形 baseline が正でない限り検定しない（順序規律）",
        capacity="S01 の増分のみ",
        ml_role="閾値の非線形は S01 の後に増分検定として",
        eligibility=ACTIVE,
        p_real=2,
        magnitude=2,
        utilisation_score=5,
        breadth_score=4,
        robustness=2,
        information_gain=2,
        turnover_cost=2,
        complexity=4,
        overfit_risk=4,
        data_burden=3,
        engineering_burden=3,
    ),
    Candidate(
        cid="S17",
        direction="G",
        name="event 日の cross-asset 共動を方向ソースにする",
        mechanism="event 日に株式・金利がどちらへ動いたかが、その後の FX の方向を決める",
        information="event カレンダー + 当日の株式・金利変化",
        target="event 通貨の 1〜5 日先",
        horizon="1〜5 日",
        architecture="event book",
        turnover="事象あたり 1 往復",
        utilisation="断続",
        breadth="8 通貨",
        data="S03・S04・S05 の合成",
        access="無料",
        overlap=("S03", "S04", "C10"),
        why_not_falsified="S03・S04 の repricing 方向が効くかを先に見るべきで、cross-asset の追加はその増分",
        capacity="S03・S04 の増分のみ",
        ml_role="不要",
        eligibility=ACTIVE,
        p_real=2,
        magnitude=2,
        utilisation_score=2,
        breadth_score=3,
        robustness=2,
        information_gain=2,
        turnover_cost=3,
        complexity=4,
        overfit_risk=4,
        data_burden=3,
        engineering_burden=3,
    ),
    Candidate(
        cid="S18",
        direction="H",
        name="retail positioning の逆張り",
        mechanism="retail の片寄りが逆方向の将来リターンに対応する",
        information="OANDA positionBook（認証要・禁止）、IG client sentiment（口座要）、Myfxbook（web、履歴なし）",
        target="pair の 1〜5 日先",
        horizon="1〜5 日",
        architecture="pair book",
        turnover="高い",
        utilisation="常時",
        breadth="20 pair（実効は少ない）",
        data="過去履歴が無料で揃わず、forward に蓄積するしかない",
        access="認証または web scraping（未承認）",
        overlap=("C20",),
        why_not_falsified="データが無い",
        capacity="—（データなし）",
        ml_role="不要",
        eligibility=BLOCKED,
        p_real=2,
        magnitude=2,
        utilisation_score=4,
        breadth_score=3,
        robustness=2,
        information_gain=3,
        turnover_cost=4,
        complexity=2,
        overfit_risk=3,
        data_burden=5,
        engineering_burden=4,
    ),
    Candidate(
        cid="S19",
        direction="H",
        name="COT の変化 × price の相互作用",
        mechanism="投機ポジションの変化と price の食い違い",
        information="CFTC COT（取得済み）",
        target="1〜4 週",
        horizon="1〜4 週",
        architecture="currency book",
        turnover="低い",
        utilisation="常時",
        breadth="7 通貨",
        data="保有",
        access="保有",
        overlap=("H-021", "C21"),
        why_not_falsified="—（H-021 で tested cells が NOT_SUPPORTED、C21 は PRIOR_FAMILY_CLOSED）",
        capacity="—",
        ml_role="—",
        eligibility=EXCLUDED,
        p_real=1,
        magnitude=1,
        utilisation_score=4,
        breadth_score=3,
        robustness=1,
        information_gain=1,
        turnover_cost=1,
        complexity=2,
        overfit_risk=4,
        data_burden=1,
        engineering_burden=1,
    ),
    Candidate(
        cid="S20",
        direction="H",
        name="FX option の risk reversal / implied vol skew",
        mechanism="option 市場の片寄りが spot の将来方向を示す",
        information="25 delta risk reversal",
        target="pair の 5〜20 日先",
        horizon="5〜20 日",
        architecture="currency book",
        turnover="中",
        utilisation="常時",
        breadth="主要 pair",
        data="無料の履歴なし（Bloomberg・CME 等の有料）",
        access="有料",
        overlap=(),
        why_not_falsified="データが無い",
        capacity="—（データなし）",
        ml_role="不要",
        eligibility=BLOCKED,
        p_real=3,
        magnitude=2,
        utilisation_score=4,
        breadth_score=3,
        robustness=2,
        information_gain=3,
        turnover_cost=2,
        complexity=2,
        overfit_risk=3,
        data_burden=5,
        engineering_burden=3,
    ),
    Candidate(
        cid="S21",
        direction="I",
        name="月末の株式相対リターンに条件付けた hedge rebalance flow",
        mechanism="月中に外国株が米国株に負ければ、海外投資家の hedge 調整で月末に USD の売買が起きる",
        information="月次の株式指数リターン",
        target="月末 fix 前後の USD",
        horizon="数時間〜1 日",
        architecture="event book",
        turnover="年 12 回 × 数 pair",
        utilisation="極めて低い",
        breadth="低い",
        data="S&P・Nikkei は無料、他は限定的",
        access="一部無料",
        overlap=("C05", "C04", "#475"),
        why_not_falsified="C05 は未実行、#475 の London fix は検出力で SUSPENDED",
        capacity="事象が年 12 回しかなく、年 5% には構造的に届かない",
        ml_role="不要",
        eligibility=ACTIVE,
        p_real=3,
        magnitude=1,
        utilisation_score=1,
        breadth_score=1,
        robustness=2,
        information_gain=2,
        turnover_cost=2,
        complexity=2,
        overfit_risk=3,
        data_burden=3,
        engineering_burden=3,
    ),
    Candidate(
        cid="S22",
        direction="I",
        name="session 間の cross-market 情報伝達（Asia→London、London→NY）",
        mechanism="前 session の非 FX 市場（株価指数先物等）の情報が次 session の FX に遅れて伝わる",
        information="intraday の株価指数先物（有料）。price のみにすると C03 と同じ",
        target="次 session 開始後数時間の通貨 return",
        horizon="数時間",
        architecture="intraday currency book",
        turnover="高い",
        utilisation="1 日 1〜2 回",
        breadth="実効 2〜4",
        data="intraday 先物は有料",
        access="有料",
        overlap=("C03", "H-002", "#475"),
        why_not_falsified="price のみの session 効果は H-002 で CLOSED、clock は #475 で SUSPENDED。非 FX の intraday 情報は未取得",
        capacity="日 1〜2 回の決定で、半減期は数時間。cost 負けの prior が強い",
        ml_role="不要",
        eligibility=BLOCKED,
        p_real=1,
        magnitude=2,
        utilisation_score=2,
        breadth_score=2,
        robustness=1,
        information_gain=2,
        turnover_cost=4,
        complexity=3,
        overfit_risk=4,
        data_burden=5,
        engineering_burden=4,
    ),
    Candidate(
        cid="S23",
        direction="A",
        name="ex-ante 実質金利差の level",
        mechanism="インフレ調整後の金利差が高い通貨が上がる",
        information="政策金利・利回り − インフレ期待",
        target="月次",
        horizon="1〜3 か月",
        architecture="currency book",
        turnover="低い",
        utilisation="常時",
        breadth="実効 4",
        data="取得済みの政策金利 + CPI",
        access="保有・無料",
        overlap=("H-016", "C22"),
        why_not_falsified="—（H-016 の carry premium は short-yen に集中して NOT_SUPPORTED、level の組み替えは隣接）",
        capacity="—",
        ml_role="—",
        eligibility=EXCLUDED,
        p_real=1,
        magnitude=2,
        utilisation_score=5,
        breadth_score=4,
        robustness=1,
        information_gain=1,
        turnover_cost=1,
        complexity=2,
        overfit_risk=3,
        data_burden=2,
        engineering_burden=1,
    ),
    Candidate(
        cid="S24",
        direction="B",
        name="volatility で timing した carry（crash risk 回避）",
        mechanism="高 vol 期に carry を減らす",
        information="carry + VIX",
        target="月次",
        horizon="1 か月",
        architecture="currency book",
        turnover="低い",
        utilisation="常時",
        breadth="実効 4",
        data="保有",
        access="保有",
        overlap=("H-016", "C22"),
        why_not_falsified="—（NOT_SUPPORTED の carry を vol filter で救済する形）",
        capacity="—",
        ml_role="—",
        eligibility=EXCLUDED,
        p_real=1,
        magnitude=2,
        utilisation_score=4,
        breadth_score=4,
        robustness=1,
        information_gain=1,
        turnover_cost=1,
        complexity=2,
        overfit_risk=4,
        data_burden=1,
        engineering_burden=1,
    ),
    Candidate(
        cid="S25",
        direction="A",
        name="中銀 balance sheet・準備資産 flow",
        mechanism="QT / QE の相対ペースと準備資産の再配分が通貨需要を動かす",
        information="中銀 balance sheet（FRED 等、週次〜月次）",
        target="3〜12 か月",
        horizon="3〜12 か月",
        architecture="currency book（低 turnover）",
        turnover="低い",
        utilisation="常時",
        breadth="主要 4〜5 中銀",
        data="無料だが月次で観測数が少ない",
        access="無料",
        overlap=(),
        why_not_falsified="未検定",
        capacity="観測数が少なく、seen の期間では検定不能。単独で年 5% の prior は低い",
        ml_role="不要",
        eligibility=ACTIVE,
        p_real=2,
        magnitude=1,
        utilisation_score=5,
        breadth_score=2,
        robustness=2,
        information_gain=2,
        turnover_cost=1,
        complexity=2,
        overfit_risk=3,
        data_burden=3,
        engineering_burden=2,
    ),
)

CANDIDATES: Final[tuple[Candidate, ...]] = C


def ranking() -> list[dict[str, object]]:
    rows = [
        {"cid": c.cid, "score": score(c), "eligibility": c.eligibility, "name": c.name}
        for c in CANDIDATES
    ]
    eligible = sorted(
        (r for r in rows if r["eligibility"] == ACTIVE), key=lambda r: (-int(r["score"]), r["cid"])
    )
    others = sorted(
        (r for r in rows if r["eligibility"] != ACTIVE), key=lambda r: (-int(r["score"]), r["cid"])
    )
    for rank, row in enumerate(eligible, start=1):
        row["rank"] = rank
    for row in others:
        row["rank"] = None
    return eligible + others


#: The proposed tracks. Chosen from the eligible top of the ranking, with S03 and
#: S04 merged into one track because they share the mechanism and the data.
PROPOSED_TRACKS: Final[tuple[tuple[str, tuple[str, ...]], ...]] = (
    ("T-R", ("S01",)),
    ("T-E", ("S03", "S04")),
    ("T-V", ("S13",)),
)


__all__ = [
    "ACTIVE",
    "BLOCKED",
    "BURDEN_WEIGHTS",
    "CANDIDATES",
    "EVIDENCE_CLASSES",
    "EVIDENCE_MAP",
    "EXCLUDED",
    "GAIN_WEIGHTS",
    "PROPOSED_TRACKS",
    "Candidate",
    "Evidence",
    "ranking",
    "score",
]
