"""OrderLifecycleService — order FSM management and atomic Outbox write (M8).

Responsibilities:
  1. Atomic order creation with Outbox event (D1 §6.6 invariant).
  2. Status transition helpers with semantic method names.

Transaction boundary (critical invariant):
  place_order_with_outbox() holds engine.begin() and writes both:
    - orders (status PENDING)
    - outbox_events (status pending, event_type ORDER_SUBMIT_REQUEST)
  in a single commit.  If either INSERT fails, the entire operation is rolled back.

Status transitions delegate to OrdersRepository.update_status() which enforces
the forward-only FSM.  RepositoryError propagates to callers.
"""

from __future__ import annotations

import json
import logging

from sqlalchemy import Engine, text

from fx_ai_trading.config.common_keys_context import CommonKeysContext
from fx_ai_trading.repositories.orders import OrdersRepository

_log = logging.getLogger(__name__)

_EVENT_TYPE_SUBMIT = "ORDER_SUBMIT_REQUEST"


class OrderLifecycleService:
    """Manages the full lifecycle of an order: creation, dispatch, and terminal states.

    Args:
        engine: SQLAlchemy Engine (used for the atomic order+outbox write).
        orders_repo: OrdersRepository for FSM status transitions.
    """

    def __init__(self, engine: Engine, orders_repo: OrdersRepository) -> None:
        self._engine = engine
        self._orders_repo = orders_repo

    # ------------------------------------------------------------------
    # Atomic creation (D1 §6.6)
    # ------------------------------------------------------------------

    def place_order_with_outbox(
        self,
        order_id: str,
        outbox_event_id: str,
        account_id: str,
        instrument: str,
        account_type: str,
        order_type: str,
        direction: str,
        units: str,
        context: CommonKeysContext,
        *,
        client_order_id: str | None = None,
        trading_signal_id: str | None = None,
        correlation_id: str | None = None,
        payload: dict | None = None,
    ) -> None:
        """Atomically write orders(PENDING) and outbox_events(ORDER_SUBMIT_REQUEST).

        Both INSERTs are wrapped in a single engine.begin() block.
        If either fails the entire transaction is rolled back.

        Args:
            order_id: ULID for the new order row (generated by caller).
            outbox_event_id: ULID for the new outbox_events row (generated by caller).
            account_id: Target account.
            instrument: e.g. 'EUR_USD'.
            account_type: 'demo' or 'live'.
            order_type: 'market' or 'limit'.
            direction: 'buy' or 'sell'.
            units: Positive numeric string.
            context: CommonKeysContext propagated through the system.
            client_order_id: Optional composite ULID identifier for idempotency.
            trading_signal_id: Optional FK to trading_signals.
            correlation_id: Optional trace identifier.
            payload: Optional dict stored as JSON in outbox_events.payload.
        """
        payload_json = json.dumps(payload, default=str) if payload is not None else None

        _log.info(
            "OrderLifecycleService.place_order_with_outbox: order_id=%s outbox_event_id=%s",
            order_id,
            outbox_event_id,
        )

        with self._engine.begin() as conn:
            conn.execute(
                text(
                    "INSERT INTO orders"
                    " (order_id, client_order_id, trading_signal_id,"
                    "  account_id, instrument, account_type, order_type,"
                    "  direction, units, correlation_id)"
                    " VALUES"
                    " (:order_id, :client_order_id, :trading_signal_id,"
                    "  :account_id, :instrument, :account_type, :order_type,"
                    "  :direction, :units, :correlation_id)"
                ),
                {
                    "order_id": order_id,
                    "client_order_id": client_order_id,
                    "trading_signal_id": trading_signal_id,
                    "account_id": account_id,
                    "instrument": instrument,
                    "account_type": account_type,
                    "order_type": order_type,
                    "direction": direction,
                    "units": units,
                    "correlation_id": correlation_id,
                },
            )
            conn.execute(
                text(
                    "INSERT INTO outbox_events"
                    " (outbox_event_id, order_id, event_type, status, payload)"
                    " VALUES (:outbox_event_id, :order_id, :event_type, 'pending', :payload)"
                ),
                {
                    "outbox_event_id": outbox_event_id,
                    "order_id": order_id,
                    "event_type": _EVENT_TYPE_SUBMIT,
                    "payload": payload_json,
                },
            )

        _log.info(
            "OrderLifecycleService: order %s and outbox event %s committed atomically",
            order_id,
            outbox_event_id,
        )

    # ------------------------------------------------------------------
    # Status transitions (FSM delegated to OrdersRepository)
    # ------------------------------------------------------------------

    def submit_order(self, order_id: str, context: CommonKeysContext) -> None:
        """Transition order from PENDING to SUBMITTED.

        Raises:
            RepositoryError: if current status is not PENDING or order not found.
        """
        _log.info("OrderLifecycleService.submit_order: order_id=%s", order_id)
        self._orders_repo.update_status(order_id, "SUBMITTED", context)

    def fill_order(self, order_id: str, context: CommonKeysContext) -> None:
        """Transition order from SUBMITTED to FILLED.

        Raises:
            RepositoryError: if current status is not SUBMITTED or order not found.
        """
        _log.info("OrderLifecycleService.fill_order: order_id=%s", order_id)
        self._orders_repo.update_status(order_id, "FILLED", context)

    def cancel_order(self, order_id: str, context: CommonKeysContext) -> None:
        """Transition order from PENDING or SUBMITTED to CANCELED.

        Raises:
            RepositoryError: if current status does not permit CANCELED.
        """
        _log.info("OrderLifecycleService.cancel_order: order_id=%s", order_id)
        self._orders_repo.update_status(order_id, "CANCELED", context)

    def fail_order(self, order_id: str, context: CommonKeysContext) -> None:
        """Transition order from PENDING or SUBMITTED to FAILED.

        Raises:
            RepositoryError: if current status does not permit FAILED.
        """
        _log.info("OrderLifecycleService.fail_order: order_id=%s", order_id)
        self._orders_repo.update_status(order_id, "FAILED", context)
