"""group e+f: execution and outcome tables

Revision ID: 0006_group_ef_execution_outcome
Revises: 0005_group_d_decision_pipeline
Create Date: 2026-04-18

Creates D1 sections 2.1.E (Execution, 4 tables) and 2.1.F (Outcome, 2 tables):

  Group E — Execution:
    #19 trading_signals    — adopted order intent (D1 'intents' physical name), AO
    #20 orders             — order record with FSM (PENDING→SUBMITTED→FILLED/CANCELED/FAILED), MUT
    #21 order_transactions — OANDA transaction stream events, AO
    #22 positions          — position timeline (append per change event), AO

  Group F — Outcome:
    #23 close_events       — exit events with full reason list (JSONB), AO
    #24 execution_metrics  — fill quality metrics (signal_age_seconds, slippage, etc.), AO

Key constraints (D1 critical):
  - orders.order_id is ULID (Text); generated by application (D1 2.1-E-1, 6.4)
  - orders.account_type column required (6.18 assertion)
  - close_events.reasons stores the full list of fired exit reasons (D1 2.1-F-1)
  - trading_signals.meta_decision_id FK -> meta_decisions (created in 0005)

Creation order respects intra-group FK dependencies:
  trading_signals -> orders -> order_transactions / positions -> close_events / execution_metrics
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "0006_group_ef_execution_outcome"
down_revision: Union[str, None] = "0005_group_d_decision_pipeline"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- trading_signals (D1 2.1.E #19, AO, Execution) ---
    # Phase 1 physical name was 'intents'; View alias added in a later revision.
    # FK -> meta_decisions (created in 0005) and instruments (0001).
    op.create_table(
        "trading_signals",
        sa.Column("trading_signal_id", sa.Text, primary_key=True),
        sa.Column(
            "meta_decision_id",
            sa.Text,
            sa.ForeignKey("meta_decisions.meta_decision_id"),
            nullable=False,
        ),
        sa.Column("cycle_id", sa.Text, nullable=False),
        sa.Column(
            "instrument",
            sa.Text,
            sa.ForeignKey("instruments.instrument"),
            nullable=False,
        ),
        sa.Column("strategy_id", sa.Text, nullable=False),
        sa.Column("signal_direction", sa.Text, nullable=False),  # 'buy'|'sell'
        sa.Column("signal_time_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.Text, nullable=True),
        sa.Column("ttl_seconds", sa.Integer, nullable=True),
    )
    op.create_index(
        "ix_trading_signals_cycle_id", "trading_signals", ["cycle_id"]
    )
    op.create_index(
        "ix_trading_signals_correlation_id", "trading_signals", ["correlation_id"]
    )

    # --- orders (D1 2.1.E #20, MUT, Execution) ---
    # order_id is ULID (Text); generated by application layer (D1 2.1-E-1, 6.4).
    # account_type column is mandatory for Phase 6.18 account_type assertion.
    # FSM: PENDING -> SUBMITTED -> FILLED | CANCELED | FAILED (no backward transitions).
    op.create_table(
        "orders",
        sa.Column("order_id", sa.Text, primary_key=True),  # ULID
        sa.Column("client_order_id", sa.Text, nullable=True),  # '{ulid}:{instrument}:{strategy_id}'
        sa.Column(
            "trading_signal_id",
            sa.Text,
            sa.ForeignKey("trading_signals.trading_signal_id"),
            nullable=True,
        ),
        sa.Column(
            "account_id",
            sa.Text,
            sa.ForeignKey("accounts.account_id"),
            nullable=False,
        ),
        sa.Column(
            "instrument",
            sa.Text,
            sa.ForeignKey("instruments.instrument"),
            nullable=False,
        ),
        sa.Column("account_type", sa.Text, nullable=False),  # 'demo'|'live' (6.18)
        sa.Column("order_type", sa.Text, nullable=False),    # 'market'|'limit'
        sa.Column("direction", sa.Text, nullable=False),     # 'buy'|'sell'
        sa.Column("units", sa.Numeric(18, 4), nullable=False),
        sa.Column(
            "status",
            sa.Text,
            nullable=False,
            server_default="PENDING",
        ),  # PENDING|SUBMITTED|FILLED|CANCELED|FAILED
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("correlation_id", sa.Text, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_orders_account_id", "orders", ["account_id"])
    op.create_index("ix_orders_correlation_id", "orders", ["correlation_id"])
    op.create_index("ix_orders_status", "orders", ["status"])

    # --- order_transactions (D1 2.1.E #21, AO, Execution) ---
    # Raw OANDA transaction stream events.
    # PK: (broker_txn_id, account_id) — globally unique per OANDA.
    op.create_table(
        "order_transactions",
        sa.Column("broker_txn_id", sa.Text, nullable=False),
        sa.Column(
            "account_id",
            sa.Text,
            sa.ForeignKey("accounts.account_id"),
            nullable=False,
        ),
        sa.Column(
            "order_id",
            sa.Text,
            sa.ForeignKey("orders.order_id"),
            nullable=True,  # nullable: some events may not map to a known order
        ),
        sa.Column("transaction_type", sa.Text, nullable=False),
        sa.Column("transaction_time_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON, nullable=True),
        sa.Column(
            "received_at_utc",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("broker_txn_id", "account_id"),
    )
    op.create_index(
        "ix_order_transactions_order_id", "order_transactions", ["order_id"]
    )

    # --- positions (D1 2.1.E #22, AO, Execution) ---
    # Append-only timeline: one row per position change event (open/add/close/swap_applied).
    # Latest state: MAX(position_snapshot_id) per instrument × account.
    op.create_table(
        "positions",
        sa.Column("position_snapshot_id", sa.Text, primary_key=True),
        sa.Column(
            "order_id",
            sa.Text,
            sa.ForeignKey("orders.order_id"),
            nullable=True,  # nullable: may reference a closed/unknown order
        ),
        sa.Column(
            "account_id",
            sa.Text,
            sa.ForeignKey("accounts.account_id"),
            nullable=False,
        ),
        sa.Column(
            "instrument",
            sa.Text,
            sa.ForeignKey("instruments.instrument"),
            nullable=False,
        ),
        sa.Column("event_type", sa.Text, nullable=False),  # 'open'|'add'|'close'|'swap_applied'
        sa.Column("units", sa.Numeric(18, 4), nullable=False),
        sa.Column("avg_price", sa.Numeric(18, 8), nullable=True),
        sa.Column("unrealized_pl", sa.Numeric(18, 8), nullable=True),
        sa.Column("realized_pl", sa.Numeric(18, 8), nullable=True),
        sa.Column("event_time_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.Text, nullable=True),
    )
    op.create_index("ix_positions_order_id", "positions", ["order_id"])
    op.create_index("ix_positions_account_instrument", "positions", ["account_id", "instrument"])

    # --- close_events (D1 2.1.F #23, AO, Decision logs) ---
    # reasons stores the full list of fired exit reasons (D1 2.1-F-1, 6.8):
    #   JSONB: [{priority, reason_code, detail}, ...]
    op.create_table(
        "close_events",
        sa.Column("close_event_id", sa.Text, primary_key=True),
        sa.Column(
            "order_id",
            sa.Text,
            sa.ForeignKey("orders.order_id"),
            nullable=False,
        ),
        sa.Column(
            "position_snapshot_id",
            sa.Text,
            sa.ForeignKey("positions.position_snapshot_id"),
            nullable=True,
        ),
        sa.Column("reasons", sa.JSON, nullable=False),  # [{priority, reason_code, detail}]
        sa.Column("primary_reason_code", sa.Text, nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pnl_realized", sa.Numeric(18, 8), nullable=True),
        sa.Column("correlation_id", sa.Text, nullable=True),
    )
    op.create_index("ix_close_events_order_id", "close_events", ["order_id"])
    op.create_index("ix_close_events_correlation_id", "close_events", ["correlation_id"])

    # --- execution_metrics (D1 2.1.F #24, AO, Decision logs) ---
    # Fill quality metrics including 6.15 SignalExpired / DeferExhausted reject reasons.
    op.create_table(
        "execution_metrics",
        sa.Column("execution_metric_id", sa.Text, primary_key=True),
        sa.Column(
            "order_id",
            sa.Text,
            sa.ForeignKey("orders.order_id"),
            nullable=True,  # nullable: metrics may be recorded before order_id is known
        ),
        sa.Column("signal_age_seconds", sa.Numeric(10, 3), nullable=True),
        sa.Column("slippage_pips", sa.Numeric(10, 4), nullable=True),
        sa.Column("latency_ms", sa.Integer, nullable=True),
        sa.Column("reject_reason", sa.Text, nullable=True),
        sa.Column("deferred_count", sa.Integer, nullable=True),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index(
        "ix_execution_metrics_order_id", "execution_metrics", ["order_id"]
    )


def downgrade() -> None:
    op.drop_index("ix_execution_metrics_order_id", table_name="execution_metrics")
    op.drop_table("execution_metrics")
    op.drop_index("ix_close_events_correlation_id", table_name="close_events")
    op.drop_index("ix_close_events_order_id", table_name="close_events")
    op.drop_table("close_events")
    op.drop_index("ix_positions_account_instrument", table_name="positions")
    op.drop_index("ix_positions_order_id", table_name="positions")
    op.drop_table("positions")
    op.drop_index("ix_order_transactions_order_id", table_name="order_transactions")
    op.drop_table("order_transactions")
    op.drop_index("ix_orders_status", table_name="orders")
    op.drop_index("ix_orders_correlation_id", table_name="orders")
    op.drop_index("ix_orders_account_id", table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_trading_signals_correlation_id", table_name="trading_signals")
    op.drop_index("ix_trading_signals_cycle_id", table_name="trading_signals")
    op.drop_table("trading_signals")
