# ruff: noqa: E501 -- mechanism prose
"""**expected-return mechanism の再設計**（2026-09-24 裁定 §9–§13）。

`NON_DECISION_BEARING_EXPLORATORY_ONLY` · `RESEARCH_SCRATCH_NON_AUTHORITATIVE`.

inventory の次順位を上から実行するのをやめ、**「なぜその情報が FX へ遅れて届き、
その遅れがなぜ retail の cost を超えて残るのか」** を mechanism ごとに書き直した。

**alpha は 1 本も見ていない。** 数値の prior は文献・データの性質・過去 cycle の
**公開済みの結論**からだけ置いてある（どの候補についても、このデータでの return は計算していない）。

過去の evidence を読み直して分かった構造上の事実を 1 つ、最初に書いておく:

> **これまでの track は、1 本を除いて `run_book` の `neutralize_leading_factor=True` で
> G10 の第 1 主成分（通常はドル方向）を落とした相対価値 book で測られている。**
> 例外は Top-Five の T5（TIC flow）だけで、ドル軸そのものを target にした
> （POSITIVE_EXPLORATORY、非 decision grade）。
> つまり **ドル factor の expected return を、金利や macro の情報で測ったことは一度も無い。**
> これは閉じた family ではなく、測定の設計がほとんど見ていなかった空白である。

水増しはしない: timeframe・smoothing・model・符号だけが違うものは別候補にしない。
有料データが要る候補も ranking に入れるが、**購入はしない**（§13）。
"""

from __future__ import annotations

from typing import Any, Final

#: template の必須 field（裁定 §11）。
TEMPLATE_FIELDS: Final[tuple[str, ...]] = (
    "mechanism_id",
    "family_letter",
    "name",
    "economic_mechanism",
    "why_fx_should_lag",
    "information_source",
    "expected_return_source",
    "target_variable",
    "horizon",
    "natural_signal_persistence",
    "expected_turnover",
    "breadth",
    "public_free_data",
    "timing_revision_quality",
    "overlap_with_prior_failures",
    "why_genuinely_new",
    "plausible_gross_edge",
    "plausible_net_edge",
    "plausible_annual_return_capacity",
    "leverage_scalability",
    "complexity",
    "overfit_risk",
    "expected_information_gain",
)

#: ranking の因子（裁定 §18）。1〜5 の順序尺度。**判断であって測定ではない。**
NUMERATOR: Final[tuple[str, ...]] = (
    "p_real_edge",
    "economic_magnitude",
    "persistence",
    "breadth_score",
    "capital_utilization",
    "information_gain",
)
DENOMINATOR: Final[tuple[str, ...]] = ("cost", "complexity_score", "overfit", "data_burden")

XS: Final[str] = "CROSS_SECTIONAL_RELATIVE_VALUE（既存 book、ドル factor を中立化）"
DOLLAR: Final[str] = "DOLLAR_FACTOR_TIME_SERIES（ドル対 7 通貨 basket、ドル factor を中立化しない）"


def _m(mid: str, letter: str, name: str, *, score: dict[str, int], **fields: Any) -> dict[str, Any]:
    row = {"mechanism_id": mid, "family_letter": letter, "name": name, **fields, "score": score}
    missing = [f for f in TEMPLATE_FIELDS if f not in row]
    if missing:
        raise ValueError(f"{mid}: template field が欠けている {missing}")
    extra = set(score) ^ set(NUMERATOR + DENOMINATOR)
    if extra:
        raise ValueError(f"{mid}: ranking 因子が合わない {sorted(extra)}")
    return row


MECHANISMS: Final[tuple[dict[str, Any], ...]] = (
    # ------------------------------------------------------------------ A
    _m(
        "M01",
        "A",
        "Taylor 則の政策圧力 gap → 通貨",
        economic_mechanism=(
            "インフレと労働市場の緩みから Taylor 則が示す政策金利と、実際の政策金利の差（gap）が大きい国は、"
            "中銀が追いつくために引き締めを続ける。その経路は将来の金利差を広げ、通貨需要を生む"
        ),
        why_fx_should_lag=(
            "市場は**いま観測できる金利差**と中銀の forward guidance に錨を下ろす。fundamentals が示す"
            "将来の政策経路は、中銀が実際に動くまで部分的にしか織り込まれない（政策の慣性と guidance への信頼）。"
            "入力は月次で公表が遅く、日々の price action に埋もれる"
        ),
        information_source="CPI 前年比（OECD MEI）、失業率（OECD 調和失業率）、中銀政策金利（OECD MEI の central bank rate）",
        expected_return_source="将来の政策金利差の拡大（carry の変化）と、それに伴う通貨の再評価",
        target_variable="通貨の cross-section 相対 excess return",
        horizon="1〜3 か月",
        natural_signal_persistence="高い（月次入力、gap は数四半期続く）",
        expected_turnover="低い（4〜8 RT/年/単位 gross）",
        breadth="G10 の 8 通貨（CHF・NZD の失業率は四半期で粗い）",
        public_free_data="ALFRED（OECD MEI）と BIS（政策金利、SDMX）。どちらも request を期間指定できる。ALFRED の政策金利は USD 以外取れず、BIS で取れた",
        timing_revision_quality="CPI はほぼ改訂無し。失業率は季節調整の改訂あり → REVISION_CAVEAT",
        overlap_with_prior_failures=(
            "S23（実質金利水準）は閉鎖、carry（#471）は NOT_SUPPORTED、S01（2 年金利 repricing）は閉鎖。"
            "**入力に市場金利を使わない**ので、どれとも情報集合が違う。U1（貿易収支）とも入力が重ならない"
        ),
        why_genuinely_new="金利の**水準**でも市場金利の**変化**でもなく、fundamentals が要求する政策と実際の政策の**ずれ**を測る。一度も測っていない",
        plausible_gross_edge="Sharpe 0.2〜0.4（Taylor-rule fundamentals の為替予測は文献で弱いが正）",
        plausible_net_edge="0.1〜0.3（低 turnover なので cost 控除は 0.1 程度）",
        plausible_annual_return_capacity="10% vol で年 1〜3%。年 5% には vol 17〜50% が要る",
        leverage_scalability="高い（低 turnover・分散された 8 通貨）",
        complexity="中（Taylor 則の係数を固定値で置く。推定しない）",
        overfit_risk="中（係数・潜在成長の置き方に自由度がある → 事前に固定）",
        expected_information_gain="高い（政策 fundamentals という未測定の情報集合を 1 回で開けられる）",
        score={
            "p_real_edge": 3,
            "economic_magnitude": 3,
            "persistence": 4,
            "breadth_score": 4,
            "capital_utilization": 4,
            "information_gain": 4,
            "cost": 2,
            "complexity_score": 3,
            "overfit": 3,
            "data_burden": 2,
        },
    ),
    _m(
        "M02",
        "A",
        "市場が織り込んだ政策経路と fundamentals の経路の乖離",
        economic_mechanism="2 年金利 − 政策金利（市場が織り込む今後の変化）と、Taylor gap（fundamentals が要求する変化）の差。市場が織り込み不足の国の通貨が後で上がる",
        why_fx_should_lag="市場の織り込みが fundamentals に遅れるなら、その差は解消に向かう。FX は短期金利の変化を通じてしか反応しない",
        information_source="G10 の日次 2 年金利（無料で期間指定できるのは USD・EUR・CAD 程度）＋ M01 の入力",
        expected_return_source="織り込み不足の解消に伴う金利差の変化",
        target_variable="通貨の cross-section 相対 excess return",
        horizon="1〜3 か月",
        natural_signal_persistence="中",
        expected_turnover="中（6〜15 RT/年）",
        breadth="無料では 3 通貨程度",
        public_free_data="**部分的**。日本・英国・豪州の 2 年金利は一括配信か 403。OIS は有料",
        timing_revision_quality="市場データは改訂無し。ただし 3 通貨では breadth 規則の下限",
        overlap_with_prior_failures="S01（日次公開 2 年金利の方向 repricing）と入力の半分を共有する。**§14 の『simple daily public-yield repricing』の言い換えにならないよう、2 年金利を単独の signal にしない**",
        why_genuinely_new="市場の織り込みと fundamentals の差という**2 つの情報集合の差分**で、どちらか一方ではない",
        plausible_gross_edge="0.2〜0.4",
        plausible_net_edge="0.0〜0.2",
        plausible_annual_return_capacity="breadth 3 では小さい",
        leverage_scalability="中",
        complexity="高い",
        overfit_risk="高い",
        expected_information_gain="中（OIS が手に入れば高い — 有料候補 M25 を参照）",
        score={
            "p_real_edge": 3,
            "economic_magnitude": 3,
            "persistence": 3,
            "breadth_score": 1,
            "capital_utilization": 2,
            "information_gain": 3,
            "cost": 3,
            "complexity_score": 4,
            "overfit": 4,
            "data_burden": 4,
        },
    ),
    # ------------------------------------------------------------------ B
    _m(
        "M03",
        "B",
        "イールドカーブの状態遷移（bull / bear × steepening / flattening）",
        economic_mechanism="曲線の動き方の状態（政策期待主導か term premium 主導か）が変わると、通貨への含意が変わる",
        why_fx_should_lag="状態の識別には数週間の観測が要り、市場は水準の変化に先に反応する",
        information_source="G10 の 3 か月金利と 10 年金利（月次、OECD MEI）",
        expected_return_source="状態遷移後の金利差の持続",
        target_variable="通貨の cross-section 相対 excess return",
        horizon="1〜3 か月",
        natural_signal_persistence="中",
        expected_turnover="中",
        breadth="8 通貨",
        public_free_data="ALFRED（月次）",
        timing_revision_quality="市場データ、改訂無し",
        overlap_with_prior_failures="**S02（曲線 slope / curvature の変化）が T3 で NOT_SUPPORTED。** 同じ 2 本の金利の状態分類は、同じ入力の非線形変換に近い",
        why_genuinely_new="状態遷移という形式は新しいが、**情報集合は S02 と同じ**。新規性は低い",
        plausible_gross_edge="0.0〜0.2",
        plausible_net_edge="負〜0.1",
        plausible_annual_return_capacity="小さい",
        leverage_scalability="中",
        complexity="高い（状態の定義に自由度）",
        overfit_risk="高い",
        expected_information_gain="低い",
        score={
            "p_real_edge": 2,
            "economic_magnitude": 2,
            "persistence": 3,
            "breadth_score": 4,
            "capital_utilization": 3,
            "information_gain": 1,
            "cost": 3,
            "complexity_score": 4,
            "overfit": 5,
            "data_burden": 2,
        },
    ),
    # ------------------------------------------------------------------ C
    _m(
        "M04",
        "C",
        "国債市場の先行（10 年金利の変化が FX に先行する）",
        economic_mechanism="債券投資家は政策と成長の情報をより早く価格に入れる。その変化が FX に数日遅れて伝わる",
        why_fx_should_lag="FX の主要参加者（実需・hedge）と債券の参加者が違い、情報の伝達に摩擦がある",
        information_source="G10 の日次 10 年金利",
        expected_return_source="金利差の変化の FX への遅れた転嫁",
        target_variable="通貨の cross-section 相対 excess return",
        horizon="数日",
        natural_signal_persistence="低い",
        expected_turnover="高い（30〜80 RT/年）",
        breadth="無料で日次が揃うのは 3〜4 通貨",
        public_free_data="部分的",
        timing_revision_quality="市場データ。取引終了時刻の不一致に注意",
        overlap_with_prior_failures="**S01（T-R）は同じ構造で半減期 1.7 日・turnover 82〜98・net 負。** 10 年に替えても機構は同じ",
        why_genuinely_new="**新しくない**。満期を替えただけで、§10 の水増しに当たる",
        plausible_gross_edge="0.1〜0.3",
        plausible_net_edge="負",
        plausible_annual_return_capacity="無い（cost が飲む）",
        leverage_scalability="低い",
        complexity="中",
        overfit_risk="中",
        expected_information_gain="低い",
        score={
            "p_real_edge": 2,
            "economic_magnitude": 2,
            "persistence": 1,
            "breadth_score": 2,
            "capital_utilization": 2,
            "information_gain": 1,
            "cost": 5,
            "complexity_score": 3,
            "overfit": 3,
            "data_burden": 3,
        },
    ),
    _m(
        "M05",
        "C",
        "株式下落 → 安全通貨の遅れた再評価",
        economic_mechanism="株式の drawdown が funding の巻き戻しを通じて安全通貨の需要を遅れて高める",
        why_fx_should_lag="leverage の巻き戻しは数日〜数週間かけて起きる",
        information_source="株価指数（日次）・VIX",
        expected_return_source="巻き戻しの持続",
        target_variable="安全通貨 vs 資源国通貨",
        horizon="数日〜数週",
        natural_signal_persistence="低〜中",
        expected_turnover="中〜高",
        breadth="1 軸（risk-on/off）",
        public_free_data="VIX は ALFRED、株価指数は license で期間が限られる",
        timing_revision_quality="市場データ",
        overlap_with_prior_failures="**S05（T1、VIX shock）が NOT_SUPPORTED、U5（信用 spread）も NOT_SUPPORTED。** 同じ risk-on/off 軸",
        why_genuinely_new="**新しくない**（§12C が求めた『単純な risk-on/off ではない』を満たさない）",
        plausible_gross_edge="0.1〜0.3",
        plausible_net_edge="負",
        plausible_annual_return_capacity="無い",
        leverage_scalability="低い",
        complexity="低い",
        overfit_risk="中",
        expected_information_gain="低い",
        score={
            "p_real_edge": 2,
            "economic_magnitude": 2,
            "persistence": 2,
            "breadth_score": 1,
            "capital_utilization": 2,
            "information_gain": 1,
            "cost": 4,
            "complexity_score": 2,
            "overfit": 3,
            "data_burden": 2,
        },
    ),
    # ------------------------------------------------------------------ D
    _m(
        "M06",
        "D",
        "通貨 network の伝播（bloc anchor から周辺通貨へ）",
        economic_mechanism="EUR→CHF、AUD→NZD のように、anchor 通貨の動きが周辺へ遅れて伝わる",
        why_fx_should_lag="周辺通貨の流動性が薄く、裁定が遅れる",
        information_source="FX 価格のみ",
        expected_return_source="伝播の遅れ",
        target_variable="周辺通貨の相対 return",
        horizon="数日",
        natural_signal_persistence="低い",
        expected_turnover="高い",
        breadth="数ペア",
        public_free_data="あり（FX 価格）",
        timing_revision_quality="問題なし",
        overlap_with_prior_failures="**S10（T4）が NOT_SUPPORTED（net −1.435 / −2.890、5 本で最悪）、H-003 型相対強弱は閉鎖。**",
        why_genuinely_new="**rename になる**（§12D の条件を満たせない）。ranking には載せるが選ばない",
        plausible_gross_edge="負〜0.1",
        plausible_net_edge="負",
        plausible_annual_return_capacity="無い",
        leverage_scalability="低い",
        complexity="低い",
        overfit_risk="高い",
        expected_information_gain="ほぼ 0",
        score={
            "p_real_edge": 1,
            "economic_magnitude": 1,
            "persistence": 1,
            "breadth_score": 2,
            "capital_utilization": 1,
            "information_gain": 1,
            "cost": 5,
            "complexity_score": 2,
            "overfit": 4,
            "data_burden": 1,
        },
    ),
    # ------------------------------------------------------------------ E
    _m(
        "M07",
        "E",
        "非同期市場の情報伝達（session handoff）",
        economic_mechanism="閉じている市場（東京・欧州の株式や債券）で起きた repricing が、FX の次の session に遅れて入る",
        why_fx_should_lag="FX は 24 時間取引なので、実は**最も速い市場**である。他市場が閉じている間の情報は FX が先に織り込む",
        information_source="M15 の FX bar と、他市場の session 終値（intraday の株価指数先物は有料）",
        expected_return_source="非同期 repricing の追随",
        target_variable="次 session の通貨 return",
        horizon="数時間〜1 日",
        natural_signal_persistence="低い",
        expected_turnover="非常に高い",
        breadth="数通貨",
        public_free_data="**無料では他市場の intraday が無い**（S22 は PAID_DATA_ONLY）。FX だけにすると clock/fix family と同じ",
        timing_revision_quality="時刻整合が難しい",
        overlap_with_prior_failures="clock/fix 系は閉鎖、Round 1 は M15 の decision scale で edge なし",
        why_genuinely_new="有料 intraday があれば新しいが、無料版は**閉じた family の言い換え**",
        plausible_gross_edge="不明",
        plausible_net_edge="負（intraday の cost）",
        plausible_annual_return_capacity="無い",
        leverage_scalability="低い",
        complexity="高い",
        overfit_risk="高い",
        expected_information_gain="低い（無料版）",
        score={
            "p_real_edge": 1,
            "economic_magnitude": 2,
            "persistence": 1,
            "breadth_score": 2,
            "capital_utilization": 1,
            "information_gain": 2,
            "cost": 5,
            "complexity_score": 4,
            "overfit": 5,
            "data_burden": 5,
        },
    ),
    # ------------------------------------------------------------------ F
    _m(
        "M08",
        "F",
        "日本の対外証券投資 flow（財務省 週次）→ JPY",
        economic_mechanism="本邦投資家の外債買い越しは円売りの実需である",
        why_fx_should_lag="週次公表で、flow の持続（年金・生保の配分変更）は数か月続く",
        information_source="財務省『対外及び対内証券売買契約等の状況』週次",
        expected_return_source="持続する flow",
        target_variable="JPY の相対 return",
        horizon="数週〜数か月",
        natural_signal_persistence="中",
        expected_turnover="低〜中",
        breadth="**1 通貨**",
        public_free_data="**一括 CSV のみ（期間指定不可）→ BULK_ONLY、今回は取得しない**",
        timing_revision_quality="週次、改訂は小さい",
        overlap_with_prior_failures="S26（US TIC）は T5 で POSITIVE_EXPLORATORY（非 decision grade）。**TIC flow の定式を JPY に移しただけ**に近い",
        why_genuinely_new="主体（本邦投資家）とデータは独立だが、breadth 1 で定式は T5 と同型",
        plausible_gross_edge="0.1〜0.4（1 通貨）",
        plausible_net_edge="0.0〜0.3",
        plausible_annual_return_capacity="1 通貨なので小さい",
        leverage_scalability="低い",
        complexity="低い",
        overfit_risk="中",
        expected_information_gain="中",
        score={
            "p_real_edge": 3,
            "economic_magnitude": 2,
            "persistence": 3,
            "breadth_score": 1,
            "capital_utilization": 1,
            "information_gain": 3,
            "cost": 2,
            "complexity_score": 2,
            "overfit": 3,
            "data_burden": 5,
        },
    ),
    _m(
        "M09",
        "F",
        "euro 圏の対外証券投資 flow（ECB 国際収支 月次）→ EUR",
        economic_mechanism="euro 圏居住者の対外証券投資の純増は EUR 売りの実需",
        why_fx_should_lag="月次・約 7 週遅れの公表で、flow は持続する",
        information_source="ECB Data Portal（BP6）",
        expected_return_source="持続する flow",
        target_variable="EUR の相対 return",
        horizon="1〜3 か月",
        natural_signal_persistence="中",
        expected_turnover="低い",
        breadth="**1 通貨**",
        public_free_data="あり（ECB API は startPeriod / endPeriod で期間指定できる）",
        timing_revision_quality="BoP は改訂が大きい → REVISION_CAVEAT",
        overlap_with_prior_failures="S26 と同型（1 地域の portfolio flow）",
        why_genuinely_new="データは独立だが breadth 1",
        plausible_gross_edge="0.1〜0.3",
        plausible_net_edge="0.0〜0.2",
        plausible_annual_return_capacity="小さい",
        leverage_scalability="低い",
        complexity="低い",
        overfit_risk="中",
        expected_information_gain="低〜中",
        score={
            "p_real_edge": 2,
            "economic_magnitude": 2,
            "persistence": 3,
            "breadth_score": 1,
            "capital_utilization": 1,
            "information_gain": 2,
            "cost": 2,
            "complexity_score": 2,
            "overfit": 3,
            "data_burden": 3,
        },
    ),
    # ------------------------------------------------------------------ G
    _m(
        "M10",
        "G",
        "FX 流動性 premium（quoted spread の相対悪化 → その後の相対 return）",
        economic_mechanism=(
            "流動性が悪化した通貨を持つ投資家は、そのリスクへの補償を要求する。"
            "流動性の悪化局面で売られた通貨は、その後 premium を払い戻す（liquidity risk premium）"
        ),
        why_fx_should_lag="流動性の悪化は強制的な売り（在庫の偏り）を伴い、裁定資本がすぐには入らない",
        information_source="**本 repo の M15 bid/ask**（OANDA の quote、20 pair）から通貨別の相対 spread",
        expected_return_source="流動性リスクへの補償",
        target_variable="通貨の cross-section 相対 excess return",
        horizon="数週〜1 か月",
        natural_signal_persistence="中（spread の状態は数週続く）",
        expected_turnover="中（8〜20 RT/年）",
        breadth="8 通貨",
        public_free_data="**既に手元にある**（seen の M15 cache）。外部取得は無い",
        timing_revision_quality="同時刻の quote で改訂無し。**recent span（約 4.7 年）しか無い**",
        overlap_with_prior_failures="spread を signal に使った track は無い。Round 1 の M15 family は**価格の向き**を使ったもので、流動性の状態ではない",
        why_genuinely_new="price の方向ではなく**取引費用の状態**という別の観測量",
        plausible_gross_edge="0.1〜0.3",
        plausible_net_edge="0.0〜0.2",
        plausible_annual_return_capacity="小〜中",
        leverage_scalability="中",
        complexity="中",
        overfit_risk="中（retail quote が interbank の流動性を表すかは不確か）",
        expected_information_gain="中（新しい観測量、ただし標本が短い）",
        score={
            "p_real_edge": 2,
            "economic_magnitude": 2,
            "persistence": 3,
            "breadth_score": 4,
            "capital_utilization": 3,
            "information_gain": 3,
            "cost": 3,
            "complexity_score": 3,
            "overfit": 3,
            "data_burden": 1,
        },
    ),
    # ------------------------------------------------------------------ H
    _m(
        "M11",
        "H",
        "macro data momentum（インフレと労働市場の変化の相対）→ 通貨",
        economic_mechanism=(
            "インフレが加速し労働市場が改善している国は、将来の引き締めと資本流入を通じて通貨が上がる。"
            "Dahlquist & Hasseltoft（2020）の economic momentum"
        ),
        why_fx_should_lag="macro の変化は月次で少しずつ公表され、投資家の注意は限られる（under-reaction）。1 つの公表では信号が弱く、累積で効く",
        information_source="CPI 前年比の 12 か月変化、失業率の 12 か月変化（OECD MEI）",
        expected_return_source="macro 改善の遅れた価格への反映",
        target_variable="通貨の cross-section 相対 excess return",
        horizon="1〜3 か月",
        natural_signal_persistence="高い",
        expected_turnover="低い（4〜8 RT/年）",
        breadth="8 通貨",
        public_free_data="ALFRED（期間指定可）",
        timing_revision_quality="失業率に季節調整の改訂 → REVISION_CAVEAT",
        overlap_with_prior_failures=(
            "**U1（貿易収支の変化）は Dahlquist–Hasseltoft の構成要素の 1 つで、NOT_SUPPORTED。** "
            "U1 の救済にならないよう、**貿易収支を入力に入れない**（feature 追加は禁止）。"
            "M01 とは入力の一部（インフレ・失業率）を共有するので、両方選ぶなら rename gate を置く"
        ),
        why_genuinely_new="インフレと労働市場の**変化**という情報集合は、どの track でも使っていない",
        plausible_gross_edge="0.2〜0.5（原論文は長期で 0.7 前後、以後の再現は弱め）",
        plausible_net_edge="0.1〜0.4",
        plausible_annual_return_capacity="10% vol で年 1〜4%",
        leverage_scalability="高い",
        complexity="低い（2 変数の等ウェイト、推定なし）",
        overfit_risk="低〜中",
        expected_information_gain="高い",
        score={
            "p_real_edge": 3,
            "economic_magnitude": 3,
            "persistence": 4,
            "breadth_score": 4,
            "capital_utilization": 4,
            "information_gain": 4,
            "cost": 2,
            "complexity_score": 2,
            "overfit": 2,
            "data_burden": 2,
        },
    ),
    _m(
        "M12",
        "H",
        "macro 予測の分散（disagreement）× surprise 状態",
        economic_mechanism="予測の不一致が大きい時の surprise は価格への影響が大きく、遅れて織り込まれる",
        why_fx_should_lag="不一致が大きいと価格発見に時間がかかる",
        information_source="survey の個別予測（Consensus Economics・Bloomberg は有料。無料は US の SPF のみ）",
        expected_return_source="surprise の遅れた織り込み",
        target_variable="通貨の相対 return",
        horizon="数週",
        natural_signal_persistence="中",
        expected_turnover="中",
        breadth="無料では US のみ",
        public_free_data="**無い**（G10 の consensus は有料）",
        timing_revision_quality="survey は改訂無し",
        overlap_with_prior_failures="#473（expectation benchmark）で survey consensus を扱った",
        why_genuinely_new="dispersion は未測定だが、データが無い",
        plausible_gross_edge="不明",
        plausible_net_edge="不明",
        plausible_annual_return_capacity="不明",
        leverage_scalability="中",
        complexity="高い",
        overfit_risk="高い",
        expected_information_gain="中（有料なら）",
        score={
            "p_real_edge": 2,
            "economic_magnitude": 2,
            "persistence": 2,
            "breadth_score": 1,
            "capital_utilization": 2,
            "information_gain": 3,
            "cost": 3,
            "complexity_score": 4,
            "overfit": 4,
            "data_burden": 5,
        },
    ),
    # ------------------------------------------------------------------ I
    _m(
        "M13",
        "I",
        "volatility 状態の遷移 × 通貨の risk beta",
        economic_mechanism="低 vol から高 vol への遷移の直後、risk beta の高い通貨はレバレッジの解消で売られ続ける",
        why_fx_should_lag="deleveraging は段階的に起きる",
        information_source="FX の realized vol と通貨ごとの beta（価格由来）",
        expected_return_source="解消の持続（volatility 自体は alpha にしない）",
        target_variable="通貨の相対 return",
        horizon="数日〜数週",
        natural_signal_persistence="中",
        expected_turnover="中〜高",
        breadth="8 通貨",
        public_free_data="あり（価格）",
        timing_revision_quality="問題なし",
        overlap_with_prior_failures="S15（vol / trend 状態遷移）未測定だが**価格由来**、S24（vol timing の carry）閉鎖、S05 NOT_SUPPORTED",
        why_genuinely_new="状態 × beta の交差項は新しいが、情報は FX 価格の中にある → incremental value の上限が低い",
        plausible_gross_edge="0.1〜0.2",
        plausible_net_edge="負〜0.1",
        plausible_annual_return_capacity="小さい",
        leverage_scalability="低い（tail が厚い）",
        complexity="中",
        overfit_risk="高い",
        expected_information_gain="低い",
        score={
            "p_real_edge": 2,
            "economic_magnitude": 2,
            "persistence": 2,
            "breadth_score": 3,
            "capital_utilization": 2,
            "information_gain": 2,
            "cost": 4,
            "complexity_score": 3,
            "overfit": 4,
            "data_burden": 1,
        },
    ),
    # ------------------------------------------------------------------ J
    _m(
        "M14",
        "J",
        "ドル funding stress（CP − T-bill spread）→ USD",
        economic_mechanism="ドル調達の逼迫は USD 需要を高め、解消とともに戻る",
        why_fx_should_lag="funding の逼迫は数週続く",
        information_source="3 か月 CP 金利 − 3 か月 T-bill（ALFRED 日次）",
        expected_return_source="funding premium",
        target_variable="ドル factor",
        horizon="数週",
        natural_signal_persistence="中",
        expected_turnover="中",
        breadth="1 factor",
        public_free_data="あり",
        timing_revision_quality="市場データ",
        overlap_with_prior_failures="**U5（HY OAS、funding stress）が NOT_SUPPORTED で cost も悪化要因。** 同じ stress 軸",
        why_genuinely_new="funding 市場の指標は信用 spread と別だが、機構は U5 と同じ",
        plausible_gross_edge="0.0〜0.2",
        plausible_net_edge="負〜0.1",
        plausible_annual_return_capacity="小さい",
        leverage_scalability="低い（stress 局面で gap）",
        complexity="低い",
        overfit_risk="中",
        expected_information_gain="低い",
        score={
            "p_real_edge": 2,
            "economic_magnitude": 2,
            "persistence": 2,
            "breadth_score": 1,
            "capital_utilization": 2,
            "information_gain": 1,
            "cost": 3,
            "complexity_score": 2,
            "overfit": 3,
            "data_burden": 2,
        },
    ),
    # ------------------------------------------------ ドル factor（新しい target）
    _m(
        "M15",
        "A",
        "dollar carry（外国の平均短期金利 − 米短期金利 → ドル factor）",
        economic_mechanism=(
            "外国の平均金利が米金利を上回る時、投資家はドルを売って basket を持つことで carry を得る。"
            "その premium はドル全体の方向に乗る（Lustig, Roussanov & Verdelhan 2014）"
        ),
        why_fx_should_lag=(
            "遅れではなく**リスク premium**である。ドル factor は世界景気のリスクを負うので、"
            "金利差が開いている間はその補償が続く。高い persistence は機構そのものから来る"
        ),
        information_source="G10 の 3 か月銀行間金利（OECD MEI 月次、米国も銀行間金利）",
        expected_return_source="ドル factor の carry premium",
        target_variable="**ドル対 7 通貨 basket の return（ドル factor）**",
        horizon="1〜3 か月",
        natural_signal_persistence="非常に高い",
        expected_turnover="非常に低い（2〜4 RT/年）",
        breadth="1 factor（7 通貨で構成）",
        public_free_data="ALFRED（期間指定可）",
        timing_revision_quality="市場金利、改訂無し",
        overlap_with_prior_failures=(
            "cross-sectional carry（#471）は NOT_SUPPORTED、S24（vol timing carry）は閉鎖。"
            "**過去の track は T5（TIC flow）を除いてドル factor を中立化した相対 book で測っている**ので、"
            "金利の情報でドル factor の time-series premium を測ったことは無い"
        ),
        why_genuinely_new="target そのものが新しい（ドル factor）。情報は金利だが、使い方が別",
        plausible_gross_edge="0.3〜0.5（原論文 1984–2011 で 0.5〜0.8、ゼロ金利期は弱い）",
        plausible_net_edge="0.3〜0.5（turnover が非常に低いので cost はほぼ効かない）",
        plausible_annual_return_capacity="10% vol で年 3〜5%",
        leverage_scalability="中（1 factor なので分散が効かない、crash risk あり）",
        complexity="低い",
        overfit_risk="低い（符号は理論で固定、閾値なし）",
        expected_information_gain="高い（測定の空白）",
        score={
            "p_real_edge": 3,
            "economic_magnitude": 4,
            "persistence": 5,
            "breadth_score": 2,
            "capital_utilization": 3,
            "information_gain": 5,
            "cost": 1,
            "complexity_score": 1,
            "overfit": 2,
            "data_burden": 2,
        },
    ),
    _m(
        "M16",
        "H",
        "米国と他国の macro momentum の差 → ドル factor",
        economic_mechanism="米国の macro（インフレ・労働市場）が他国より速く改善すると、ドル全体が上がる",
        why_fx_should_lag="M11 と同じ under-reaction。ドル factor は相対 book では捨てられていた（T5 は flow 情報でドル軸を測ったが、macro では無い）",
        information_source="M11 と同じ入力（米国 vs 他 7 通貨の平均）",
        expected_return_source="macro 改善の遅れた反映（ドル全体）",
        target_variable="ドル factor",
        horizon="1〜3 か月",
        natural_signal_persistence="高い",
        expected_turnover="低い",
        breadth="1 factor",
        public_free_data="ALFRED",
        timing_revision_quality="REVISION_CAVEAT（失業率）",
        overlap_with_prior_failures="M11 と入力を共有する。**M11 と同時に選ぶ場合、M11 の USD 成分と重なる**",
        why_genuinely_new="target が新しい（ドル factor）",
        plausible_gross_edge="0.1〜0.4",
        plausible_net_edge="0.1〜0.3",
        plausible_annual_return_capacity="10% vol で年 1〜3%",
        leverage_scalability="中",
        complexity="低い",
        overfit_risk="低〜中",
        expected_information_gain="中（M11 と入力が重なる分だけ下がる）",
        score={
            "p_real_edge": 3,
            "economic_magnitude": 3,
            "persistence": 4,
            "breadth_score": 2,
            "capital_utilization": 3,
            "information_gain": 3,
            "cost": 1,
            "complexity_score": 2,
            "overfit": 2,
            "data_burden": 2,
        },
    ),
    _m(
        "M17",
        "H",
        "経済政策不確実性（EPU）の相対水準 → 通貨の risk premium",
        economic_mechanism=(
            "政策不確実性が相対的に高い国の通貨は、投資家がそのリスクの補償を求めるので、"
            "価格が下がった後に高い期待 return を持つ（不確実性 premium）"
        ),
        why_fx_should_lag="不確実性の premium は解消まで続く（遅れではなくリスクの補償）",
        information_source="Baker–Bloom–Davis の EPU 指数（新聞記事の計数、月次、ALFRED で配信）",
        expected_return_source="不確実性リスクの premium",
        target_variable="通貨の cross-section 相対 excess return",
        horizon="1〜3 か月",
        natural_signal_persistence="中〜高",
        expected_turnover="中（6〜12 RT/年）",
        breadth="EPU がある国（US・欧州・日本・英国・カナダ・豪州 など、Stage 0 で確認）",
        public_free_data="ALFRED（期間指定可）",
        timing_revision_quality="記事計数の再集計で小さな改訂 → REVISION_CAVEAT。公表は翌月初",
        overlap_with_prior_failures="U3（中銀声明の tone）は**中銀の文書**、EPU は**新聞全体の不確実性語**。情報源も機構も違う",
        why_genuinely_new="不確実性を risk premium として扱う track は無い",
        plausible_gross_edge="0.0〜0.3（文献は同時点の関係が中心で、予測力の証拠は弱い）",
        plausible_net_edge="負〜0.2",
        plausible_annual_return_capacity="小さい",
        leverage_scalability="中",
        complexity="低い",
        overfit_risk="中（**符号の理論が 2 通りある**: 同時点で下落 / 後で premium。後者を凍結する）",
        expected_information_gain="中",
        score={
            "p_real_edge": 2,
            "economic_magnitude": 2,
            "persistence": 3,
            "breadth_score": 3,
            "capital_utilization": 3,
            "information_gain": 3,
            "cost": 2,
            "complexity_score": 2,
            "overfit": 3,
            "data_burden": 2,
        },
    ),
    _m(
        "M18",
        "H",
        "景気循環の先行指標（OECD CLI）の point-in-time momentum",
        economic_mechanism="景気の転換点を先に示す CLI が上向いた国は、成長と引き締めの期待で通貨が上がる",
        why_fx_should_lag="転換点は事後にしか確定せず、市場は確認を待つ",
        information_source="OECD CLI（ALFRED の vintage）",
        expected_return_source="成長期待の遅れた反映",
        target_variable="通貨の相対 return",
        horizon="1〜3 か月",
        natural_signal_persistence="高い",
        expected_turnover="低い",
        breadth="8 通貨",
        public_free_data="ALFRED。ただし **CLI は trend filter の端点問題で大きく改訂される**",
        timing_revision_quality="**現行 vintage は look-ahead を含む**。point-in-time の再構成には vintage ごとの request が数百回要る",
        overlap_with_prior_failures="M11 と同じ『成長 momentum』の別指標",
        why_genuinely_new="指標は新しいが、機構は M11 と同じ",
        plausible_gross_edge="0.1〜0.4",
        plausible_net_edge="0.1〜0.3",
        plausible_annual_return_capacity="小〜中",
        leverage_scalability="中",
        complexity="高い（vintage の再構成）",
        overfit_risk="中",
        expected_information_gain="中（M11 と重なる）",
        score={
            "p_real_edge": 2,
            "economic_magnitude": 3,
            "persistence": 4,
            "breadth_score": 4,
            "capital_utilization": 3,
            "information_gain": 2,
            "cost": 2,
            "complexity_score": 4,
            "overfit": 3,
            "data_burden": 5,
        },
    ),
    _m(
        "M19",
        "B",
        "市場のインフレ期待（breakeven）の repricing",
        economic_mechanism="期待インフレの上昇は引き締め期待を通じて通貨を押し上げる",
        why_fx_should_lag="—",
        information_source="breakeven",
        expected_return_source="—",
        target_variable="—",
        horizon="—",
        natural_signal_persistence="—",
        expected_turnover="—",
        breadth="—",
        public_free_data="—",
        timing_revision_quality="—",
        overlap_with_prior_failures="**S28 は family 境界の内側として閉鎖済み**",
        why_genuinely_new="**新しくない。閉鎖済み**。網羅性のためだけに載せる",
        plausible_gross_edge="—",
        plausible_net_edge="—",
        plausible_annual_return_capacity="—",
        leverage_scalability="—",
        complexity="—",
        overfit_risk="—",
        expected_information_gain="0",
        score={
            "p_real_edge": 1,
            "economic_magnitude": 1,
            "persistence": 1,
            "breadth_score": 1,
            "capital_utilization": 1,
            "information_gain": 1,
            "cost": 3,
            "complexity_score": 3,
            "overfit": 5,
            "data_burden": 3,
        },
    ),
    _m(
        "M20",
        "C",
        "交易条件指数（輸出物価 / 輸入物価）の momentum",
        economic_mechanism="交易条件の改善は所得と通貨需要を増やす",
        why_fx_should_lag="物価指数は月次で遅れて公表される",
        information_source="輸出入物価指数（OECD MEI）",
        expected_return_source="交易条件の遅れた反映",
        target_variable="通貨の相対 return",
        horizon="1〜3 か月",
        natural_signal_persistence="高い",
        expected_turnover="低い",
        breadth="8 通貨（系列の揃い方は未確認）",
        public_free_data="ALFRED（一部）",
        timing_revision_quality="REVISION_CAVEAT",
        overlap_with_prior_failures="**S06（T2、商品価格の交易条件）は NOT_SUPPORTED で、T1 を超える incremental IC が負。** 物価指数に替えても機構は同じ",
        why_genuinely_new="**低い**（データ源の置き換え）",
        plausible_gross_edge="0.0〜0.2",
        plausible_net_edge="負〜0.1",
        plausible_annual_return_capacity="小さい",
        leverage_scalability="中",
        complexity="低い",
        overfit_risk="中",
        expected_information_gain="低い",
        score={
            "p_real_edge": 2,
            "economic_magnitude": 2,
            "persistence": 4,
            "breadth_score": 3,
            "capital_utilization": 3,
            "information_gain": 1,
            "cost": 2,
            "complexity_score": 2,
            "overfit": 3,
            "data_burden": 3,
        },
    ),
    _m(
        "M21",
        "A",
        "政策の循環状態（利上げ / 利下げの連続）→ 通貨",
        economic_mechanism="中銀は同じ方向に続けて動く。循環の途中にある国の通貨は、残りの動きを織り込み切れていない",
        why_fx_should_lag="市場は次の 1 回を織り込むが、循環全体の長さは過小評価する",
        information_source="政策金利の変更履歴",
        expected_return_source="残りの循環の織り込み",
        target_variable="通貨の相対 return",
        horizon="1〜6 か月",
        natural_signal_persistence="非常に高い",
        expected_turnover="低い",
        breadth="8 通貨",
        public_free_data="あり",
        timing_revision_quality="改訂無し",
        overlap_with_prior_failures="**C01（決定そのもの）と H-019（会合日の値動き）で扱った。** 決定の累積は C01 の情報の和",
        why_genuinely_new="低い（C01 の情報集合の再集計）",
        plausible_gross_edge="0.1〜0.3",
        plausible_net_edge="0.0〜0.2",
        plausible_annual_return_capacity="小さい",
        leverage_scalability="中",
        complexity="低い",
        overfit_risk="中",
        expected_information_gain="低い",
        score={
            "p_real_edge": 2,
            "economic_magnitude": 2,
            "persistence": 5,
            "breadth_score": 4,
            "capital_utilization": 3,
            "information_gain": 1,
            "cost": 1,
            "complexity_score": 2,
            "overfit": 3,
            "data_burden": 2,
        },
    ),
    _m(
        "M22",
        "F",
        "季節的な本国送金（日本の年度末・配当期）",
        economic_mechanism="年度末の本国送金や配当の送金は暦で決まった flow",
        why_fx_should_lag="暦で分かっているので、むしろ前倒しで織り込まれる",
        information_source="暦",
        expected_return_source="予定された flow",
        target_variable="JPY",
        horizon="数週",
        natural_signal_persistence="—",
        expected_turnover="低い",
        breadth="1 通貨",
        public_free_data="あり",
        timing_revision_quality="—",
        overlap_with_prior_failures="clock/fix・暦系は閉鎖、S21（月末 rebalance）は停止中",
        why_genuinely_new="低い。**event 数が span ごとに 5〜17 回しかなく**、過剰適合の危険が最も高い",
        plausible_gross_edge="不明",
        plausible_net_edge="不明",
        plausible_annual_return_capacity="小さい",
        leverage_scalability="低い",
        complexity="低い",
        overfit_risk="非常に高い",
        expected_information_gain="低い",
        score={
            "p_real_edge": 1,
            "economic_magnitude": 2,
            "persistence": 1,
            "breadth_score": 1,
            "capital_utilization": 1,
            "information_gain": 1,
            "cost": 2,
            "complexity_score": 1,
            "overfit": 5,
            "data_burden": 1,
        },
    ),
    _m(
        "M23",
        "H",
        "財政収支の momentum → 通貨",
        economic_mechanism="財政赤字の拡大は国債増発・リスク premium を通じて通貨に効く（符号は理論上どちらもあり得る）",
        why_fx_should_lag="四半期公表で遅い",
        information_source="一般政府収支（四半期）",
        expected_return_source="不明確",
        target_variable="通貨の相対 return",
        horizon="四半期",
        natural_signal_persistence="非常に高い",
        expected_turnover="非常に低い",
        breadth="8 通貨（系列の揃い方は未確認）",
        public_free_data="部分的",
        timing_revision_quality="**改訂が大きい**、公表が 3〜6 か月遅れ",
        overlap_with_prior_failures="無い",
        why_genuinely_new="新しいが、**符号の理論が定まらない**",
        plausible_gross_edge="不明",
        plausible_net_edge="不明",
        plausible_annual_return_capacity="小さい",
        leverage_scalability="中",
        complexity="中",
        overfit_risk="高い（符号を決めきれない）",
        expected_information_gain="低い（四半期で event 数が少ない）",
        score={
            "p_real_edge": 1,
            "economic_magnitude": 2,
            "persistence": 5,
            "breadth_score": 3,
            "capital_utilization": 2,
            "information_gain": 2,
            "cost": 1,
            "complexity_score": 3,
            "overfit": 4,
            "data_burden": 4,
        },
    ),
    # ------------------------------------------------------------ 有料データの候補
    _m(
        "M24",
        "I",
        "FX option の risk reversal / skew の変化 → 方向",
        economic_mechanism="option 市場の tail 需要は、spot に先行して方向の偏りを示す",
        why_fx_should_lag="option 参加者は hedge 需要を先に表す",
        information_source="25 delta risk reversal（有料）",
        expected_return_source="tail 需要の spot への波及",
        target_variable="通貨の相対 return",
        horizon="数日〜数週",
        natural_signal_persistence="中",
        expected_turnover="中",
        breadth="8 通貨",
        public_free_data="**無い（PAID）**",
        timing_revision_quality="市場データ",
        overlap_with_prior_failures="S20（PAID_DATA_ONLY）",
        why_genuinely_new="option 市場の情報は一度も入っていない",
        plausible_gross_edge="0.2〜0.5",
        plausible_net_edge="0.1〜0.3",
        plausible_annual_return_capacity="中",
        leverage_scalability="中",
        complexity="中",
        overfit_risk="中",
        expected_information_gain="高い",
        score={
            "p_real_edge": 3,
            "economic_magnitude": 3,
            "persistence": 2,
            "breadth_score": 4,
            "capital_utilization": 3,
            "information_gain": 4,
            "cost": 3,
            "complexity_score": 3,
            "overfit": 3,
            "data_burden": 5,
        },
    ),
    _m(
        "M25",
        "A",
        "OIS が織り込む政策経路の変化 → 通貨",
        economic_mechanism="OIS は政策経路の市場期待そのもの。その変化は FX の金利要因を直接表す",
        why_fx_should_lag="S01 と同じ問い。OIS なら 2 年金利の term premium の雑音を除ける",
        information_source="G10 の OIS curve（有料）",
        expected_return_source="政策経路の repricing",
        target_variable="通貨の相対 return",
        horizon="数日〜数週",
        natural_signal_persistence="中",
        expected_turnover="中〜高",
        breadth="8 通貨",
        public_free_data="**無い（PAID）**",
        timing_revision_quality="市場データ",
        overlap_with_prior_failures="S01 は 2 年金利で閉鎖。**OIS で同じ定式を回すと S01 の rename の危険**。M02 の形（fundamentals との差）で使うべき",
        why_genuinely_new="term premium を除いた政策期待という点で情報は増えるが、定式次第",
        plausible_gross_edge="0.2〜0.4",
        plausible_net_edge="0.0〜0.2",
        plausible_annual_return_capacity="中",
        leverage_scalability="中",
        complexity="中",
        overfit_risk="中",
        expected_information_gain="中〜高",
        score={
            "p_real_edge": 3,
            "economic_magnitude": 3,
            "persistence": 3,
            "breadth_score": 4,
            "capital_utilization": 3,
            "information_gain": 3,
            "cost": 3,
            "complexity_score": 3,
            "overfit": 3,
            "data_burden": 5,
        },
    ),
    _m(
        "M26",
        "G",
        "CME FX 先物の intraday 出来高と order flow",
        economic_mechanism="取引所の出来高と約定方向は、相対取引の FX で見えない order flow の proxy（Evans–Lyons）",
        why_fx_should_lag="order flow の情報は分散して到着し、価格に遅れて入る",
        information_source="CME FX 先物の tick / intraday（有料）",
        expected_return_source="order flow の価格 impact",
        target_variable="通貨の相対 return",
        horizon="数時間〜数日",
        natural_signal_persistence="低い",
        expected_turnover="高い",
        breadth="主要 6〜7 通貨",
        public_free_data="**無い（PAID）**",
        timing_revision_quality="市場データ",
        overlap_with_prior_failures="S22（PAID_DATA_ONLY）",
        why_genuinely_new="order flow は一度も入っていない",
        plausible_gross_edge="0.3〜0.8（短期）",
        plausible_net_edge="負〜0.2（retail の cost）",
        plausible_annual_return_capacity="cost 次第",
        leverage_scalability="低い",
        complexity="高い",
        overfit_risk="高い",
        expected_information_gain="中",
        score={
            "p_real_edge": 3,
            "economic_magnitude": 3,
            "persistence": 1,
            "breadth_score": 3,
            "capital_utilization": 2,
            "information_gain": 3,
            "cost": 5,
            "complexity_score": 4,
            "overfit": 4,
            "data_burden": 5,
        },
    ),
    _m(
        "M27",
        "F",
        "機関投資家の FX flow / positioning（CLS の flow・銀行の顧客 flow）",
        economic_mechanism="実際の顧客 flow の偏りは持続し、価格を押す",
        why_fx_should_lag="flow は分散して執行される",
        information_source="CLS FX flow データ、銀行の顧客 flow（有料）",
        expected_return_source="flow の持続",
        target_variable="通貨の相対 return",
        horizon="数日〜数週",
        natural_signal_persistence="中",
        expected_turnover="中",
        breadth="8 通貨",
        public_free_data="**無い（PAID）**。無料の COT は S19 で閉鎖",
        timing_revision_quality="provider 次第",
        overlap_with_prior_failures="**COT の rename にしないこと**（§14）。CLS は実際の決済 flow で、先物 positioning ではない",
        why_genuinely_new="実決済の flow は一度も入っていない",
        plausible_gross_edge="0.2〜0.5",
        plausible_net_edge="0.1〜0.3",
        plausible_annual_return_capacity="中",
        leverage_scalability="中",
        complexity="中",
        overfit_risk="中",
        expected_information_gain="高い",
        score={
            "p_real_edge": 3,
            "economic_magnitude": 3,
            "persistence": 3,
            "breadth_score": 4,
            "capital_utilization": 3,
            "information_gain": 4,
            "cost": 3,
            "complexity_score": 3,
            "overfit": 3,
            "data_burden": 5,
        },
    ),
)

#: 有料データの design-only 整理（裁定 §13）。**購入しない。** 費用は公開の料金表で確かめて
#: いない**桁の目安**であり、見積もりではない。
PAID_DATA: Final[dict[str, dict[str, str]]] = {
    "M24": {
        "provider": "Bloomberg / LSEG（Refinitiv）/ CME の FX option データ",
        "rough_cost": "年間 数百万円〜（端末契約に付随）。**未確認の桁の目安**",
        "coverage": "G10 の 1M/3M 25d RR・ATM vol、2000 年代前半から",
        "exact_information": "tail hedge 需要の方向と大きさ",
        "public_substitute": "無い（CBOE の通貨 vol 指数は廃止済み）",
        "expected_information_gain": "高い",
    },
    "M25": {
        "provider": "Bloomberg / LSEG / ICE の OIS curve",
        "rough_cost": "同上（端末または data license）",
        "coverage": "G10、2000 年代後半から",
        "exact_information": "term premium を除いた政策経路の期待",
        "public_substitute": "2 年国債金利（term premium を含む、S01 で閉鎖）",
        "expected_information_gain": "中〜高（M02 の形で使う場合）",
    },
    "M26": {
        "provider": "CME DataMine",
        "rough_cost": "月額 数万〜数十万円（データ量次第）。**未確認**",
        "coverage": "主要 FX 先物、tick",
        "exact_information": "取引所での約定方向と出来高",
        "public_substitute": "無い",
        "expected_information_gain": "中（retail の cost で短期 edge を取れるかが別問題）",
    },
    "M27": {
        "provider": "CLS（Nasdaq Data Link 経由など）",
        "rough_cost": "年間 数百万円〜。**未確認**",
        "coverage": "主要通貨の決済 flow、2010 年代から",
        "exact_information": "実決済の買い / 売りの偏り",
        "public_substitute": "COT（先物 positioning、S19 で閉鎖）",
        "expected_information_gain": "高い",
    },
    "M12": {
        "provider": "Consensus Economics / Bloomberg ECO",
        "rough_cost": "年間 数十万〜数百万円。**未確認**",
        "coverage": "G10 の主要指標の個別予測",
        "exact_information": "予測の分散と surprise",
        "public_substitute": "US の SPF のみ",
        "expected_information_gain": "中",
    },
}


def by_id() -> dict[str, dict[str, Any]]:
    return {row["mechanism_id"]: row for row in MECHANISMS}


__all__ = [
    "DENOMINATOR",
    "DOLLAR",
    "MECHANISMS",
    "NUMERATOR",
    "PAID_DATA",
    "TEMPLATE_FIELDS",
    "XS",
    "by_id",
]
