"""PlaceOrderUseCase — end-to-end order placement flow (D3 §2.9.1).

Flow:
  1. Validate units > 0
  2. Validate direction in ('buy', 'sell')
  3. Verify account exists and account_type matches
  4. Create order (status PENDING via DB default)
  5. Record position snapshot (buy → 'open', sell → 'close')

CommonKeysContext flows from caller → UseCase → Service → Repository.
External API calls, risk management, and ULID generation are out of scope.
"""

from __future__ import annotations

from fx_ai_trading.config.common_keys_context import CommonKeysContext
from fx_ai_trading.services.account_service import AccountService
from fx_ai_trading.services.order_service import OrderService
from fx_ai_trading.services.position_service import PositionService

_VALID_DIRECTIONS = frozenset({"buy", "sell"})
_DIRECTION_TO_EVENT = {"buy": "open", "sell": "close"}


class PlaceOrderUseCase:
    """Orchestrates the order placement flow."""

    def __init__(
        self,
        account_service: AccountService,
        order_service: OrderService,
        position_service: PositionService,
    ) -> None:
        self._accounts = account_service
        self._orders = order_service
        self._positions = position_service

    def execute(
        self,
        order_id: str,
        position_snapshot_id: str,
        account_id: str,
        instrument: str,
        account_type: str,
        order_type: str,
        direction: str,
        units: str,
        context: CommonKeysContext,
        *,
        correlation_id: str | None = None,
    ) -> None:
        """Execute the place-order flow.

        Args:
            order_id: ULID generated by caller.
            position_snapshot_id: ULID for the position event.
            account_id: Target account.
            instrument: e.g. 'EUR_USD'.
            account_type: Must match the account row ('demo' or 'live').
            order_type: 'market' or 'limit'.
            direction: 'buy' or 'sell'.
            units: Positive numeric string, e.g. '1000'.
            context: CommonKeysContext propagated to all write operations.
            correlation_id: Optional trace identifier.

        Raises:
            ValueError: If validation fails.
        """
        self._validate_units(units)
        self._validate_direction(direction)
        self._validate_account(account_id, account_type)

        self._orders.create_order(
            order_id=order_id,
            account_id=account_id,
            instrument=instrument,
            account_type=account_type,
            order_type=order_type,
            direction=direction,
            units=units,
            context=context,
            correlation_id=correlation_id,
        )

        event_type = _DIRECTION_TO_EVENT[direction]
        self._positions.record_position_event(
            position_snapshot_id=position_snapshot_id,
            account_id=account_id,
            instrument=instrument,
            event_type=event_type,
            units=units,
            context=context,
            order_id=order_id,
            correlation_id=correlation_id,
        )

    def _validate_units(self, units: str) -> None:
        try:
            value = float(units)
        except (ValueError, TypeError) as exc:
            raise ValueError(f"units must be a positive number, got {units!r}") from exc
        if value <= 0:
            raise ValueError(f"units must be > 0, got {value}")

    def _validate_direction(self, direction: str) -> None:
        if direction not in _VALID_DIRECTIONS:
            raise ValueError(
                f"direction must be one of {sorted(_VALID_DIRECTIONS)}, got {direction!r}"
            )

    def _validate_account(self, account_id: str, account_type: str) -> None:
        account = self._accounts.get_account(account_id)
        if account is None:
            raise ValueError(f"account not found: {account_id!r}")
        if account["account_type"] != account_type:
            raise ValueError(
                f"account_type mismatch: order has {account_type!r}"
                f" but account {account_id!r} has {account['account_type']!r}"
            )
